/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.14 at 08:00:25 AM CEST
//
package com.hybris.cockpitng.config.explorertree.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for dynamic-node complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="dynamic-node"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/explorertree}explorer-node"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="dynamic-node-parameter" type="{http://www.hybris.com/cockpitng/config/explorertree}parameter"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="populator-bean-id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="populator-class-name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="indexing-depth" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="hide-root-node" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dynamic-node", propOrder = {"dynamicNodeParameter"})
public class DynamicNode extends ExplorerNode
{
    @XmlElement(name = "dynamic-node-parameter")
    protected List<Parameter> dynamicNodeParameter;
    @XmlAttribute(name = "populator-bean-id")
    protected String populatorBeanId;
    @XmlAttribute(name = "populator-class-name")
    protected String populatorClassName;
    @XmlAttribute(name = "indexing-depth")
    protected Integer indexingDepth;
    @XmlAttribute(name = "hide-root-node")
    protected Boolean hideRootNode;


    /**
     * Gets the value of the dynamicNodeParameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dynamicNodeParameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getDynamicNodeParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     *
     *
     */
    public List<Parameter> getDynamicNodeParameter()
    {
        if(dynamicNodeParameter == null)
        {
            dynamicNodeParameter = new ArrayList<Parameter>();
        }
        return this.dynamicNodeParameter;
    }


    /**
     * Gets the value of the populatorBeanId property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getPopulatorBeanId()
    {
        return populatorBeanId;
    }


    /**
     * Sets the value of the populatorBeanId property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setPopulatorBeanId(String value)
    {
        this.populatorBeanId = value;
    }


    /**
     * Gets the value of the populatorClassName property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getPopulatorClassName()
    {
        return populatorClassName;
    }


    /**
     * Sets the value of the populatorClassName property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setPopulatorClassName(String value)
    {
        this.populatorClassName = value;
    }


    /**
     * Gets the value of the indexingDepth property.
     *
     * @return
     *            possible object is
     *         {@link Integer }
     *
     */
    public Integer getIndexingDepth()
    {
        return indexingDepth;
    }


    /**
     * Sets the value of the indexingDepth property.
     *
     * @param value
     *           allowed object is
     *           {@link Integer }
     *
     */
    public void setIndexingDepth(Integer value)
    {
        this.indexingDepth = value;
    }


    /**
     * Gets the value of the hideRootNode property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isHideRootNode()
    {
        return hideRootNode;
    }


    /**
     * Sets the value of the hideRootNode property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setHideRootNode(final Boolean value)
    {
        this.hideRootNode = value;
    }
}
