/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.09 at 12:26:23 PM CET 
//
package com.hybris.cockpitng.config.explorertree.jaxb;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="navigation-node" type="{http://www.hybris.com/cockpitng/config/explorertree}navigation-node"/&gt;
 *           &lt;element name="type-node" type="{http://www.hybris.com/cockpitng/config/explorertree}type-node"/&gt;
 *           &lt;element name="dynamic-node" type="{http://www.hybris.com/cockpitng/config/explorertree}dynamic-node"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
                "navigationNodeOrTypeNodeOrDynamicNode"
})
@XmlRootElement(name = "explorer-tree")
public class ExplorerTree
{
    @XmlElements({
                    @XmlElement(name = "navigation-node", type = NavigationNode.class),
                    @XmlElement(name = "type-node", type = TypeNode.class),
                    @XmlElement(name = "dynamic-node", type = DynamicNode.class)
    })
    @Mergeable(key = "id")
    protected List<ExplorerNode> navigationNodeOrTypeNodeOrDynamicNode;
    @XmlAttribute(name = "title")
    protected String title;


    /**
     * Gets the value of the navigationNodeOrTypeNodeOrDynamicNode property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the navigationNodeOrTypeNodeOrDynamicNode property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNavigationNodeOrTypeNodeOrDynamicNode().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NavigationNode }
     * {@link TypeNode }
     * {@link DynamicNode }
     *
     *
     */
    public List<ExplorerNode> getNavigationNodeOrTypeNodeOrDynamicNode()
    {
        if(navigationNodeOrTypeNodeOrDynamicNode == null)
        {
            navigationNodeOrTypeNodeOrDynamicNode = new ArrayList<ExplorerNode>();
        }
        return this.navigationNodeOrTypeNodeOrDynamicNode;
    }


    /**
     * Gets the value of the title property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitle()
    {
        return title;
    }


    /**
     * Sets the value of the title property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitle(String value)
    {
        this.title = value;
    }
}
