/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 01:41:50 PM CET 
//
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hybris.com/cockpitng/config/explorertree", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hybris.cockpitng.config.explorertree.jaxb;
