/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.10.17 at 04:10:47 PM EDT
//
package com.hybris.cockpitng.config.explorertree.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for parameter complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="parameter"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.hybris.com/cockpitng/config/explorertree}name"/&gt;
 *         &lt;element name="value" type="{http://www.hybris.com/cockpitng/config/explorertree}value"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parameter", propOrder = {"name", "value"})
public class Parameter
{
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String value;


    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getName()
    {
        return this.name;
    }


    /**
     * Gets the value of the value property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValue()
    {
        return this.value;
    }


    /**
     * Sets the value of the name property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setName(final String value)
    {
        this.name = value;
    }


    /**
     * Sets the value of the value property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setValue(final String value)
    {
        this.value = value;
    }
}
