/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.10.17 at 04:10:47 PM EDT
//
package com.hybris.cockpitng.config.explorertree.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for type-node complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="type-node"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/explorertree}explorer-node"&gt;
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "type-node")
public class TypeNode extends ExplorerNode
{
    private static final long serialVersionUID = 1L;
    @XmlAttribute(name = "code")
    protected String code;


    /**
     * Gets the value of the code property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCode()
    {
        return this.code;
    }


    /**
     * Sets the value of the code property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setCode(final String value)
    {
        this.code = value;
    }
}
