/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.14 at 03:53:29 PM CEST 
//
package com.hybris.cockpitng.config.notification.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for NotificationDestination complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="NotificationDestination"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="level" use="required" type="{http://www.hybris.com/cockpitng/config/notifications}ImportanceLevel" /&gt;
 *       &lt;attribute name="destination" type="{http://www.hybris.com/cockpitng/config/notifications}Destination" default="GLOBAL" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificationDestination")
public class NotificationDestination
{
    @XmlAttribute(name = "level", required = true)
    protected ImportanceLevel level;
    @XmlAttribute(name = "destination")
    protected Destination destination;


    /**
     * Gets the value of the level property.
     *
     * @return
     *     possible object is
     *     {@link ImportanceLevel }
     *
     */
    public ImportanceLevel getLevel()
    {
        return level;
    }


    /**
     * Sets the value of the level property.
     *
     * @param value
     *     allowed object is
     *     {@link ImportanceLevel }
     *
     */
    public void setLevel(ImportanceLevel value)
    {
        this.level = value;
    }


    /**
     * Gets the value of the destination property.
     *
     * @return
     *     possible object is
     *     {@link Destination }
     *
     */
    public Destination getDestination()
    {
        if(destination == null)
        {
            return Destination.GLOBAL;
        }
        else
        {
            return destination;
        }
    }


    /**
     * Sets the value of the destination property.
     *
     * @param value
     *     allowed object is
     *     {@link Destination }
     *
     */
    public void setDestination(Destination value)
    {
        this.destination = value;
    }
}
