/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.10.14 at 03:53:29 PM CEST
//
package com.hybris.cockpitng.config.notification.jaxb;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for NotificationDefaults complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="NotificationDefaults"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fallback" type="{http://www.hybris.com/cockpitng/config/notifications}NotificationRenderingInfo" minOccurs="0"/&gt;
 *         &lt;element name="timeouts" type="{http://www.hybris.com/cockpitng/config/notifications}NotificationTimeouts" minOccurs="0"/&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="destinations" type="{http://www.hybris.com/cockpitng/config/notifications}NotificationDestination" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="linksEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificationDefaults", propOrder = {
                "fallback",
                "timeouts",
                "destinations"
})
public class NotificationDefaults
{
    protected NotificationRenderingInfo fallback;
    protected NotificationTimeouts timeouts;
    @Mergeable(key = "level")
    protected List<NotificationDestination> destinations;
    @XmlAttribute(name = "linksEnabled")
    protected Boolean linksEnabled;


    /**
     * Gets the value of the fallback property.
     *
     * @return
     *     possible object is
     *     {@link NotificationRenderingInfo }
     *
     */
    public NotificationRenderingInfo getFallback()
    {
        return fallback;
    }


    /**
     * Sets the value of the fallback property.
     *
     * @param value
     *     allowed object is
     *     {@link NotificationRenderingInfo }
     *
     */
    public void setFallback(NotificationRenderingInfo value)
    {
        this.fallback = value;
    }


    /**
     * Gets the value of the timeouts property.
     *
     * @return
     *     possible object is
     *     {@link NotificationTimeouts }
     *
     */
    public NotificationTimeouts getTimeouts()
    {
        return timeouts;
    }


    /**
     * Sets the value of the timeouts property.
     *
     * @param value
     *     allowed object is
     *     {@link NotificationTimeouts }
     *
     */
    public void setTimeouts(NotificationTimeouts value)
    {
        this.timeouts = value;
    }


    /**
     * Gets the value of the destinations property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destinations property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestinations().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotificationDestination }
     *
     *
     */
    public List<NotificationDestination> getDestinations()
    {
        if(destinations == null)
        {
            destinations = new ArrayList<NotificationDestination>();
        }
        return this.destinations;
    }


    /**
     * Gets the value of the linksEnabled property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isLinksEnabled()
    {
        if(linksEnabled == null)
        {
            return false;
        }
        else
        {
            return linksEnabled;
        }
    }


    /**
     * Sets the value of the linksEnabled property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setLinksEnabled(Boolean value)
    {
        this.linksEnabled = value;
    }
}
