package de.hybris.platform.payment.dto;

public enum AvsComponents
{
    POSTAL_CODE_MATCHED, POSTAL_CODE_NOT_MATCHED, ADDRESS_MATCHED, ADDRESS_NOT_MATCHED, CPF_MATCHED, CPF_NOT_MATCHED, POSTAL_CODE_9_MATCHED, POSTAL_CODE_9_NOT_MATCHED, POSTAL_CODE_5_MATCHED, POSTAL_CODE_5_NOT_MATCHED;
}
