/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.10.14 at 12:51:47 PM CEST
//
package com.hybris.cockpitng.core.config.impl.jaxb.hybris.advancedsearch;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="field-list" type="{http://www.hybris.com/cockpitng/config/advancedsearch}FieldListType"/&gt;
 *         &lt;element name="sort-field" type="{http://www.hybris.com/cockpitng/config/advancedsearch}SortFieldType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="connection-operator" type="{http://www.hybris.com/cockpitng/config/advancedsearch}ConnectionOperatorType" default="AND" /&gt;
 *       &lt;attribute name="disable-auto-search" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="disable-simple-search" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
                "fieldList",
                "sortField"
})
@XmlRootElement(name = "advanced-search", namespace = "http://www.hybris.com/cockpitng/config/advancedsearch")
public class AdvancedSearch
{
    @Mergeable(key = {})
    @XmlElement(name = "field-list", namespace = "http://www.hybris.com/cockpitng/config/advancedsearch", required = true)
    protected FieldListType fieldList;
    @XmlElement(name = "sort-field", namespace = "http://www.hybris.com/cockpitng/config/advancedsearch")
    protected SortFieldType sortField;
    @XmlAttribute(name = "connection-operator")
    protected ConnectionOperatorType connectionOperator;
    @XmlAttribute(name = "disable-auto-search")
    protected Boolean disableAutoSearch;
    @XmlAttribute(name = "disable-simple-search")
    protected Boolean disableSimpleSearch;


    /**
     * Gets the value of the fieldList property.
     *
     * @return
     *     possible object is
     *     {@link FieldListType }
     *
     */
    public FieldListType getFieldList()
    {
        return fieldList;
    }


    /**
     * Sets the value of the fieldList property.
     *
     * @param value
     *     allowed object is
     *     {@link FieldListType }
     *
     */
    public void setFieldList(FieldListType value)
    {
        this.fieldList = value;
    }


    /**
     * Gets the value of the sortField property.
     *
     * @return
     *     possible object is
     *     {@link SortFieldType }
     *
     */
    public SortFieldType getSortField()
    {
        return sortField;
    }


    /**
     * Sets the value of the sortField property.
     *
     * @param value
     *     allowed object is
     *     {@link SortFieldType }
     *
     */
    public void setSortField(SortFieldType value)
    {
        this.sortField = value;
    }


    /**
     * Gets the value of the connectionOperator property.
     *
     * @return
     *     possible object is
     *     {@link ConnectionOperatorType }
     *
     */
    public ConnectionOperatorType getConnectionOperator()
    {
        if(connectionOperator == null)
        {
            return ConnectionOperatorType.AND;
        }
        else
        {
            return connectionOperator;
        }
    }


    /**
     * Sets the value of the connectionOperator property.
     *
     * @param value
     *     allowed object is
     *     {@link ConnectionOperatorType }
     *
     */
    public void setConnectionOperator(ConnectionOperatorType value)
    {
        this.connectionOperator = value;
    }


    /**
     * Gets the value of the autoSearch property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isDisableAutoSearch()
    {
        if(disableAutoSearch == null)
        {
            return false;
        }
        else
        {
            return disableAutoSearch;
        }
    }


    /**
     * Sets the value of the autoSearch property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDisableAutoSearch(Boolean value)
    {
        this.disableAutoSearch = value;
    }


    /**
     * Gets the value of the disableSimpleSearch property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isDisableSimpleSearch()
    {
        if(disableSimpleSearch == null)
        {
            return false;
        }
        else
        {
            return disableSimpleSearch;
        }
    }


    /**
     * Sets the value of the disableSimpleSearch property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDisableSimpleSearch(Boolean value)
    {
        this.disableSimpleSearch = value;
    }
}
