/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.10.14 at 12:51:47 PM CEST
//
package com.hybris.cockpitng.core.config.impl.jaxb.hybris.advancedsearch;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ConnectionOperatorType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="ConnectionOperatorType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AND"/&gt;
 *     &lt;enumeration value="OR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "ConnectionOperatorType", namespace = "http://www.hybris.com/cockpitng/config/advancedsearch")
@XmlEnum
public enum ConnectionOperatorType
{
    AND,
    OR;


    public String value()
    {
        return name();
    }


    public static ConnectionOperatorType fromValue(String v)
    {
        return valueOf(v);
    }
}
