/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.12.08 at 02:36:32 PM CET
//
package com.hybris.cockpitng.core.config.impl.jaxb.hybris.advancedsearch;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for FieldListType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FieldListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="field" type="{http://www.hybris.com/cockpitng/config/advancedsearch}FieldType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="includeSubtypes" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="includeSubtypesCheckboxEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FieldListType", namespace = "http://www.hybris.com/cockpitng/config/advancedsearch", propOrder = {
                "field"
})
public class FieldListType
{
    @XmlElement(namespace = "http://www.hybris.com/cockpitng/config/advancedsearch")
    @Mergeable(key = "name")
    protected List<FieldType> field;
    @XmlAttribute(name = "includeSubtypes")
    protected Boolean includeSubtypes;
    @XmlAttribute(name = "disable-subtypes-checkbox")
    protected Boolean disableSubtypesCheckbox;
    @XmlAttribute(name = "disable-attributes-comparator")
    protected Boolean disableAttributesComparator;


    /**
     * Gets the value of the field property.
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldType }
     */
    public List<FieldType> getField()
    {
        if(field == null)
        {
            field = new ArrayList<FieldType>();
        }
        return this.field;
    }


    /**
     * Gets the value of the includeSubtypes property.
     * @return
     *     possible object is
     *     {@link Boolean }
     */
    public boolean isIncludeSubtypes()
    {
        if(includeSubtypes == null)
        {
            return true;
        }
        else
        {
            return includeSubtypes;
        }
    }


    /**
     * Sets the value of the includeSubtypes property.
     * @param value
     *     allowed object is
     *     {@link Boolean }
     */
    public void setIncludeSubtypes(Boolean value)
    {
        this.includeSubtypes = value;
    }


    /**
     * Gets the value of the includeSubtypesCheckboxEnabled property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isDisableSubtypesCheckbox()
    {
        if(disableSubtypesCheckbox == null)
        {
            return false;
        }
        else
        {
            return disableSubtypesCheckbox;
        }
    }


    /**
     * Sets the value of the includeSubtypesCheckboxEnabled property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDisableSubtypesCheckbox(Boolean value)
    {
        this.disableSubtypesCheckbox = value;
    }


    /**
     * Gets the value of the attributeComparatorsEnabled property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isDisableAttributesComparator()
    {
        if(disableAttributesComparator == null)
        {
            return false;
        }
        else
        {
            return disableAttributesComparator;
        }
    }


    /**
     * Sets the value of the attributeComparatorsEnabled property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDisableAttributesComparator(Boolean value)
    {
        this.disableAttributesComparator = value;
    }
}
