/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.27 at 12:05:21 PM CET
//
package com.hybris.cockpitng.core.config.impl.jaxb.hybris.advancedsearch;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.hybris.cockpitng.core.config.impl.jaxb.hybris.advancedsearch package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory
{
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hybris.cockpitng.core.config.impl.jaxb.hybris.advancedsearch
     *
     */
    public ObjectFactory()
    {
        // default constructor
    }


    /**
     * Create an instance of {@link AdvancedSearch }
     *
     */
    public AdvancedSearch createAdvancedSearch()
    {
        return new AdvancedSearch();
    }


    /**
     * Create an instance of {@link FieldListType }
     *
     */
    public FieldListType createFieldListType()
    {
        return new FieldListType();
    }


    /**
     * Create an instance of {@link SortFieldType }
     *
     */
    public SortFieldType createSortFieldType()
    {
        return new SortFieldType();
    }


    /**
     * Create an instance of {@link FieldType }
     *
     */
    public FieldType createFieldType()
    {
        return new FieldType();
    }


    /**
     * Create an instance of {@link Parameter }
     *
     */
    public Parameter createParameter()
    {
        return new Parameter();
    }
}
