/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.21 at 01:55:02 PM CET
//
package com.hybris.cockpitng.core.config.impl.jaxb.hybris;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for base complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="base"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="labels" type="{http://www.hybris.com/cockpit/config/hybris}labels" minOccurs="0"/&gt;
 *         &lt;element name="preview" type="{http://www.hybris.com/cockpit/config/hybris}preview"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "base", propOrder = {
})
@XmlRootElement(name = "base")
public class Base
{
    protected Labels labels;
    @XmlElement(required = true)
    protected Preview preview;


    /**
     * Gets the value of the labels property.
     *
     * @return
     *     possible object is
     *     {@link Labels }
     *
     */
    public Labels getLabels()
    {
        return labels;
    }


    /**
     * Sets the value of the labels property.
     *
     * @param value
     *     allowed object is
     *     {@link Labels }
     *
     */
    public void setLabels(Labels value)
    {
        this.labels = value;
    }


    /**
     * Gets the value of the preview property.
     *
     * @return
     *     possible object is
     *     {@link Preview }
     *
     */
    public Preview getPreview()
    {
        return preview;
    }


    /**
     * Sets the value of the preview property.
     *
     * @param value
     *     allowed object is
     *     {@link Preview }
     *
     */
    public void setPreview(Preview value)
    {
        this.preview = value;
    }
}
