/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.08.09 at 03:36:48 PM EDT
//
package com.hybris.cockpitng.core.config.impl.jaxb.hybris;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for editor-group complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="editor-group"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="property" type="{http://www.hybris.com/cockpit/config/hybris}editor-property" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="qualifier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" /&gt;
 *       &lt;attribute name="merge-mode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "editor-group", propOrder = {"label", "property"})
public class EditorGroup
{
    @XmlElement(required = true)
    protected String label;
    @XmlElement(required = true)
    @Mergeable(key = "qualifier")
    protected List<EditorProperty> property;
    @XmlAttribute(name = "qualifier", required = true)
    protected String qualifier;
    @XmlAttribute(name = "visible")
    protected Boolean visible;
    @XmlAttribute(name = "position")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger position;
    @XmlAttribute(name = "merge-mode")
    protected String mergeMode;


    /**
     * Gets the value of the label property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getLabel()
    {
        return label;
    }


    /**
     * Sets the value of the label property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setLabel(final String value)
    {
        this.label = value;
    }


    /**
     * Gets the value of the property property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the property property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getProperty().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link EditorProperty }
     *
     *
     */
    public List<EditorProperty> getProperty()
    {
        if(property == null)
        {
            property = new ArrayList<EditorProperty>();
        }
        return this.property;
    }


    /**
     * Gets the value of the qualifier property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getQualifier()
    {
        return qualifier;
    }


    /**
     * Sets the value of the qualifier property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setQualifier(final String value)
    {
        this.qualifier = value;
    }


    /**
     * Gets the value of the visible property.
     *
     * @return
     *         possible object is {@link Boolean }
     *
     */
    public boolean isVisible()
    {
        if(visible == null)
        {
            return true;
        }
        else
        {
            return visible;
        }
    }


    /**
     * Sets the value of the visible property.
     *
     * @param value
     *           allowed object is {@link Boolean }
     *
     */
    public void setVisible(final Boolean value)
    {
        this.visible = value;
    }


    /**
     * Gets the value of the position property.
     *
     * @return
     *         possible object is {@link BigInteger }
     *
     */
    public BigInteger getPosition()
    {
        if(position == null)
        {
            return BigInteger.ONE;
        }
        else
        {
            return position;
        }
    }


    /**
     * Sets the value of the position property.
     *
     * @param value
     *           allowed object is {@link BigInteger }
     *
     */
    public void setPosition(final BigInteger value)
    {
        this.position = value;
    }


    /**
     * Gets the value of the mergeMode property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getMergeMode()
    {
        return mergeMode;
    }


    /**
     * Sets the value of the mergeMode property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setMergeMode(final String value)
    {
        this.mergeMode = value;
    }
}
