/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.24 at 04:47:44 PM CEST
//
package com.hybris.cockpitng.core.config.impl.jaxb.hybris;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for labels complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="labels"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="shortLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="iconPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="beanId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "labels", propOrder = {
})
public class Labels
{
    protected String label;
    protected String shortLabel;
    protected String description;
    protected String iconPath;
    @XmlAttribute(name = "beanId")
    protected String beanId;


    /**
     * Gets the value of the label property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getLabel()
    {
        return label;
    }


    /**
     * Sets the value of the label property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setLabel(final String value)
    {
        this.label = value;
    }


    /**
     * Gets the value of the shortLabel property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getShortLabel()
    {
        return shortLabel;
    }


    /**
     * Sets the value of the shortLabel property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setShortLabel(final String value)
    {
        this.shortLabel = value;
    }


    /**
     * Gets the value of the description property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getDescription()
    {
        return description;
    }


    /**
     * Sets the value of the description property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setDescription(final String value)
    {
        this.description = value;
    }


    /**
     * Gets the value of the iconPath property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getIconPath()
    {
        return iconPath;
    }


    /**
     * Sets the value of the iconPath property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setIconPath(final String value)
    {
        this.iconPath = value;
    }


    /**
     * Gets the value of the beanId property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getBeanId()
    {
        return beanId;
    }


    /**
     * Sets the value of the beanId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setBeanId(final String value)
    {
        this.beanId = value;
    }
}
