/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.11.03 at 05:23:39 PM CET
//
package com.hybris.cockpitng.core.config.impl.jaxb.hybris;

/**
 * @deprecated since 2005, use {@link com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Parameter}
 */
@Deprecated(since = "2005", forRemoval = true)
public class Parameter extends com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Parameter
{
}
