/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.21 at 01:55:02 PM CET
//
package com.hybris.cockpitng.core.config.impl.jaxb.hybris;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for preview complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="preview"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="fallbackToIcon" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="urlQualifier" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "preview")
public class Preview
{
    @XmlAttribute(name = "fallbackToIcon")
    protected Boolean fallbackToIcon;
    @XmlAttribute(name = "urlQualifier")
    protected String urlQualifier;


    /**
     * Gets the value of the fallbackToIcon property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isFallbackToIcon()
    {
        if(fallbackToIcon == null)
        {
            return false;
        }
        else
        {
            return fallbackToIcon;
        }
    }


    /**
     * Sets the value of the fallbackToIcon property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setFallbackToIcon(Boolean value)
    {
        this.fallbackToIcon = value;
    }


    /**
     * Gets the value of the urlQualifier property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUrlQualifier()
    {
        return urlQualifier;
    }


    /**
     * Sets the value of the urlQualifier property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUrlQualifier(String value)
    {
        this.urlQualifier = value;
    }
}
