/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.09 at 12:09:33 PM CET 
//
package com.hybris.cockpitng.config.jaxb.wizard;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CancelType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CancelType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/wizard-config}AbstractActionType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="revert" type="{http://www.hybris.com/cockpitng/config/wizard-config}RevertType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancelType", propOrder =
                {"revert"}, namespace = "http://www.hybris.com/cockpitng/config/wizard-config")
public class CancelType extends AbstractActionType
{
    @XmlElement(required = true)
    protected List<RevertType> revert;


    /**
     * Gets the value of the revert property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * revert property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getRevert().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link RevertType }
     */
    public List<RevertType> getRevert()
    {
        if(revert == null)
        {
            revert = new ArrayList<RevertType>();
        }
        return this.revert;
    }
}
