/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.31 at 11:24:28 AM CET 
//
package com.hybris.cockpitng.config.jaxb.wizard;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ComposedHandlerType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ComposedHandlerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="additionalParams" type="{http://www.hybris.com/cockpitng/config/wizard-config}AdditionalParamType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="handlerBean" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="handlerId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComposedHandlerType", namespace = "http://www.hybris.com/cockpitng/config/wizard-config", propOrder =
                {"additionalParams"})
public class ComposedHandlerType
{
    @XmlElement(required = true)
    protected List<AdditionalParamType> additionalParams;
    @XmlAttribute(name = "handlerBean", required = true)
    protected String handlerBean;
    @XmlAttribute(name = "handlerId", required = true)
    protected String handlerId;


    /**
     * Gets the value of the additionalParams property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * additionalParams property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getAdditionalParams().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link AdditionalParamType }
     */
    public List<AdditionalParamType> getAdditionalParams()
    {
        if(additionalParams == null)
        {
            additionalParams = new ArrayList<AdditionalParamType>();
        }
        return this.additionalParams;
    }


    /**
     * Gets the value of the handlerBean property.
     *
     * @return possible object is {@link String }
     */
    public String getHandlerBean()
    {
        return handlerBean;
    }


    /**
     * Sets the value of the handlerBean property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setHandlerBean(String value)
    {
        this.handlerBean = value;
    }


    /**
     * Gets the value of the handlerId property.
     *
     * @return possible object is {@link String }
     */
    public String getHandlerId()
    {
        return handlerId;
    }


    /**
     * Sets the value of the handlerId property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setHandlerId(String value)
    {
        this.handlerId = value;
    }
}
