/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 09:44:00 AM CEST 
//
package com.hybris.cockpitng.config.jaxb.wizard;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for CustomType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CustomType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/wizard-config}AbstractActionType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="parameter" type="{http://www.hybris.com/cockpitng/config/wizard-config}parameter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="handler" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="composedHandler" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="align"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="left"/&gt;
 *             &lt;enumeration value="right"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="primary" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="validate-visible-only" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomType", propOrder = {
                "parameter"
})
public class CustomType
                extends AbstractActionType
{
    protected List<Parameter> parameter;
    @XmlAttribute(name = "label", required = true)
    protected String label;
    @XmlAttribute(name = "handler")
    protected String handler;
    @XmlAttribute(name = "composedHandler")
    protected String composedHandler;
    @XmlAttribute(name = "align")
    protected String align;
    @XmlAttribute(name = "primary")
    protected Boolean primary;
    @XmlAttribute(name = "validate-visible-only")
    protected Boolean validateVisibleOnly;


    /**
     * Gets the value of the parameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     *
     *
     */
    public List<Parameter> getParameter()
    {
        if(parameter == null)
        {
            parameter = new ArrayList<Parameter>();
        }
        return this.parameter;
    }


    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel()
    {
        return label;
    }


    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value)
    {
        this.label = value;
    }


    /**
     * Gets the value of the handler property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHandler()
    {
        return handler;
    }


    /**
     * Sets the value of the handler property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHandler(String value)
    {
        this.handler = value;
    }


    /**
     * Gets the value of the composedHandler property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getComposedHandler()
    {
        return composedHandler;
    }


    /**
     * Sets the value of the composedHandler property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setComposedHandler(String value)
    {
        this.composedHandler = value;
    }


    /**
     * Gets the value of the align property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAlign()
    {
        return align;
    }


    /**
     * Sets the value of the align property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAlign(String value)
    {
        this.align = value;
    }


    /**
     * Gets the value of the primary property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean getPrimary()
    {
        return primary;
    }


    /**
     * Sets the value of the primary property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setPrimary(Boolean value)
    {
        this.primary = value;
    }


    /**
     * Gets the value of the validateVisibleOnly property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isValidateVisibleOnly()
    {
        if(validateVisibleOnly == null)
        {
            return false;
        }
        else
        {
            return validateVisibleOnly;
        }
    }


    /**
     * Sets the value of the validateVisibleOnly property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setValidateVisibleOnly(Boolean value)
    {
        this.validateVisibleOnly = value;
    }
}
