/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.16 at 10:28:24 PM CET
//
package com.hybris.cockpitng.config.jaxb.wizard;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for DoneType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DoneType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/wizard-config}AbstractActionType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="assign" type="{http://www.hybris.com/cockpitng/config/wizard-config}AssignType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoneType", propOrder = {
                "assign"
})
public class DoneType
                extends AbstractActionType
{
    @XmlElement(namespace = "http://www.hybris.com/cockpitng/config/wizard-config")
    @Mergeable(key = {"property", "lang"})
    protected List<AssignType> assign;


    /**
     * Gets the value of the assign property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assign property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssign().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssignType }
     *
     *
     */
    public List<AssignType> getAssign()
    {
        if(assign == null)
        {
            assign = new ArrayList<AssignType>();
        }
        return this.assign;
    }
}
