/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.08.28 at 11:27:46 AM CEST
//
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hybris.com/cockpitng/config/wizard-config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hybris.cockpitng.config.jaxb.wizard;
