/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.02.06 at 03:50:50 PM CET
//
package com.hybris.cockpitng.core.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ComponentDefinition complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ComponentDefinition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentDefinition")
@XmlSeeAlso({WidgetDefinition.class})
public abstract class ComponentDefinition
{
    @XmlAttribute(name = "id", required = false)
    protected String id;
    @XmlAttribute(name = "extends", required = false)
    private String parent;


    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId()
    {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setId(final String value)
    {
        this.id = value;
    }


    public String getParent()
    {
        return parent;
    }


    public void setParent(final String parent)
    {
        this.parent = parent;
    }


    public abstract void setSettings(final Settings value);


    public abstract String getName();


    public abstract void setName(final String value);


    public abstract String getDescription();


    public abstract void setDescription(final String value);


    public abstract String getAuthor();


    public abstract void setAuthor(final String value);


    public abstract String getVersion();


    public abstract void setVersion(final String value);


    public abstract Keywords getKeywords();


    public abstract void setKeywords(final Keywords value);


    public abstract Settings getSettings();


    public abstract Sockets getSockets();


    public abstract void setSockets(final Sockets value);
}
