/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.03.07 at 03:46:32 PM CET
//
package com.hybris.cockpitng.core.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EditorDefinition complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EditorDefinition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}ComponentDefinition"&gt;
 *       &lt;all&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{}keywords" minOccurs="0"/&gt;
 *         &lt;element ref="{}settings" minOccurs="0"/&gt;
 *         &lt;element ref="{}view" minOccurs="0"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="editorClassName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element ref="{}sockets" minOccurs="0"/&gt;
 *         &lt;element name="handlesLocalization" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EditorDefinition", propOrder =
                {"name", "description", "author", "version", "keywords", "settings", "view", "type", "editorClassName", "sockets",
                                "handlesLocalization"})
@XmlRootElement(name = "editor-definition")
public class EditorDefinition extends ComponentDefinition
{
    protected String name;
    protected String description;
    protected String author;
    protected String version;
    protected Keywords keywords;
    protected Settings settings;
    protected View view;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String editorClassName;
    protected Sockets sockets;
    protected Boolean handlesLocalization;


    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     */
    @Override
    public String getName()
    {
        return name;
    }


    /**
     * Sets the value of the name property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    @Override
    public void setName(String value)
    {
        this.name = value;
    }


    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link String }
     */
    @Override
    public String getDescription()
    {
        return description;
    }


    /**
     * Sets the value of the description property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    @Override
    public void setDescription(String value)
    {
        this.description = value;
    }


    /**
     * Gets the value of the author property.
     *
     * @return possible object is {@link String }
     */
    @Override
    public String getAuthor()
    {
        return author;
    }


    /**
     * Sets the value of the author property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    @Override
    public void setAuthor(String value)
    {
        this.author = value;
    }


    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link String }
     */
    @Override
    public String getVersion()
    {
        return version;
    }


    /**
     * Sets the value of the version property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    @Override
    public void setVersion(String value)
    {
        this.version = value;
    }


    /**
     * Gets the value of the keywords property.
     *
     * @return possible object is {@link Keywords }
     */
    @Override
    public Keywords getKeywords()
    {
        return keywords;
    }


    /**
     * Sets the value of the keywords property.
     *
     * @param value
     *           allowed object is {@link Keywords }
     */
    @Override
    public void setKeywords(Keywords value)
    {
        this.keywords = value;
    }


    /**
     * Gets the value of the settings property.
     *
     * @return possible object is {@link Settings }
     */
    @Override
    public Settings getSettings()
    {
        return settings;
    }


    /**
     * Sets the value of the settings property.
     *
     * @param value
     *           allowed object is {@link Settings }
     */
    @Override
    public void setSettings(Settings value)
    {
        this.settings = value;
    }


    /**
     * Gets the value of the view property.
     *
     * @return possible object is {@link View }
     */
    public View getView()
    {
        return view;
    }


    /**
     * Sets the value of the view property.
     *
     * @param value
     *           allowed object is {@link View }
     */
    public void setView(View value)
    {
        this.view = value;
    }


    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     */
    public String getType()
    {
        return type;
    }


    /**
     * Sets the value of the type property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setType(String value)
    {
        this.type = value;
    }


    /**
     * Gets the value of the editorClassName property.
     *
     * @return possible object is {@link String }
     */
    public String getEditorClassName()
    {
        return editorClassName;
    }


    /**
     * Sets the value of the editorClassName property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setEditorClassName(String value)
    {
        this.editorClassName = value;
    }


    /**
     * Gets the value of the sockets property.
     *
     * @return possible object is {@link Sockets }
     */
    @Override
    public Sockets getSockets()
    {
        return sockets;
    }


    /**
     * Sets the value of the sockets property.
     *
     * @param value
     *           allowed object is {@link Sockets }
     */
    @Override
    public void setSockets(Sockets value)
    {
        this.sockets = value;
    }


    /**
     * Gets the value of the handlesLocalization property.
     *
     * @return possible object is {@link Boolean }
     */
    public Boolean isHandlesLocalization()
    {
        return handlesLocalization;
    }


    /**
     * Sets the value of the handlesLocalization property.
     *
     * @param value
     *           allowed object is {@link Boolean }
     */
    public void setHandlesLocalization(Boolean value)
    {
        this.handlesLocalization = value;
    }
}
