/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.02.06 at 03:50:50 PM CET
//
package com.hybris.cockpitng.core.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="input" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="output" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Forward")
@XmlRootElement(name = "forward")
public class Forward
{
    @XmlAttribute(name = "input", required = true)
    protected String input;
    @XmlAttribute(name = "output", required = true)
    protected String output;


    /**
     * Gets the value of the input property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getInput()
    {
        return input;
    }


    /**
     * Sets the value of the input property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setInput(final String value)
    {
        this.input = value;
    }


    /**
     * Gets the value of the output property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getOutput()
    {
        return output;
    }


    /**
     * Sets the value of the output property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setOutput(final String value)
    {
        this.output = value;
    }
}
