/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.02.06 at 03:50:50 PM CET
//
package com.hybris.cockpitng.core.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="default-value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "setting")
public class Setting
{
    @XmlAttribute(name = "default-value")
    protected String defaultValue;
    @XmlAttribute(name = "key", required = true)
    protected String key;
    @XmlAttribute(name = "type")
    protected String type;


    /**
     * Gets the value of the defaultValue property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDefaultValue()
    {
        return defaultValue;
    }


    /**
     * Sets the value of the defaultValue property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setDefaultValue(final String value)
    {
        this.defaultValue = value;
    }


    /**
     * Gets the value of the key property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getKey()
    {
        return key;
    }


    /**
     * Sets the value of the key property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setKey(final String value)
    {
        this.key = value;
    }


    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getType()
    {
        return type;
    }


    /**
     * Sets the value of the type property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setType(final String value)
    {
        this.type = value;
    }
}
