/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.02.06 at 03:50:50 PM CET
//
package com.hybris.cockpitng.core.impl.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SocketMultiplicity.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="SocketMultiplicity"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Collection"/&gt;
 *     &lt;enumeration value="List"/&gt;
 *     &lt;enumeration value="Set"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "SocketMultiplicity")
@XmlEnum
public enum SocketMultiplicity
{
    @XmlEnumValue("Collection")
    COLLECTION("Collection"), @XmlEnumValue("List")
LIST("List"), @XmlEnumValue("Set")
SET("Set");
    private final String value;


    SocketMultiplicity(final String value)
    {
        this.value = value;
    }


    public String value()
    {
        return value;
    }


    public static SocketMultiplicity fromValue(final String fromVal)
    {
        for(final SocketMultiplicity c : SocketMultiplicity.values())
        {
            if(c.value.equals(fromVal))
            {
                return c;
            }
        }
        throw new IllegalArgumentException(fromVal);
    }
}
