/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.02.06 at 03:50:50 PM CET
//
package com.hybris.cockpitng.core.impl.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="input" type="{}Socket" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="output" type="{}Socket" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}forward" maxOccurs="unbounded" minOccurs="0"&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"input", "output", "forward"})
@XmlRootElement(name = "sockets")
public class Sockets
{
    protected List<Socket> input;
    protected List<Socket> output;
    protected List<Forward> forward;


    /**
     * Gets the value of the input property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the input property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getInput().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Socket }
     *
     *
     */
    public List<Socket> getInput()
    {
        if(input == null)
        {
            input = new ArrayList<Socket>();
        }
        return this.input;
    }


    /**
     * Gets the value of the output property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the output property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getOutput().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Socket }
     *
     *
     */
    public List<Socket> getOutput()
    {
        if(output == null)
        {
            output = new ArrayList<Socket>();
        }
        return this.output;
    }


    /**
     * Gets the value of the forward property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the forward property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getForward().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Forward }
     *
     *
     */
    public List<Forward> getForward()
    {
        if(forward == null)
        {
            forward = new ArrayList<Forward>();
        }
        return this.forward;
    }
}
