/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.02.06 at 03:50:50 PM CET
//
package com.hybris.cockpitng.core.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Socket complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Socket"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="multiplicity" type="{}SocketMultiplicity" /&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="visibility" type="{}SocketVisibility" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Socket")
public class Socket
{
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "multiplicity")
    protected SocketMultiplicity multiplicity;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "visibility")
    protected SocketVisibility visibility;


    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId()
    {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setId(final String value)
    {
        this.id = value;
    }


    /**
     * Gets the value of the multiplicity property.
     *
     * @return possible object is {@link SocketMultiplicity }
     *
     */
    public SocketMultiplicity getMultiplicity()
    {
        return multiplicity;
    }


    /**
     * Sets the value of the multiplicity property.
     *
     * @param value
     *           allowed object is {@link SocketMultiplicity }
     *
     */
    public void setMultiplicity(final SocketMultiplicity value)
    {
        this.multiplicity = value;
    }


    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getType()
    {
        return type;
    }


    /**
     * Sets the value of the type property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setType(final String value)
    {
        this.type = value;
    }


    /**
     * Gets the value of the visibility property.
     *
     * @return possible object is {@link SocketVisibility }
     *
     */
    public SocketVisibility getVisibility()
    {
        return visibility;
    }


    /**
     * Sets the value of the visibility property.
     *
     * @param value
     *           allowed object is {@link SocketVisibility }
     *
     */
    public void setVisibility(final SocketVisibility value)
    {
        this.visibility = value;
    }
}
