/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.31 at 01:20:01 PM CEST 
//
package com.hybris.cockpitng.core.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for WidgetDefinition complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="WidgetDefinition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}ComponentDefinition"&gt;
 *       &lt;all&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{}keywords" minOccurs="0"/&gt;
 *         &lt;element ref="{}settings" minOccurs="0"/&gt;
 *         &lt;element name="defaultTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{}view" minOccurs="0"/&gt;
 *         &lt;element ref="{}controller" minOccurs="0"/&gt;
 *         &lt;element ref="{}sockets" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WidgetDefinition", propOrder = {
                "name",
                "description",
                "author",
                "version",
                "keywords",
                "settings",
                "defaultTitle",
                "view",
                "controller",
                "sockets"
})
@XmlRootElement(name = "widget-definition")
public class WidgetDefinition
                extends ComponentDefinition
{
    protected String name;
    protected String description;
    protected String author;
    protected String version;
    protected Keywords keywords;
    protected Settings settings;
    protected String defaultTitle;
    protected View view;
    protected Controller controller;
    protected Sockets sockets;


    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Override
    public String getName()
    {
        return name;
    }


    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Override
    public void setName(String value)
    {
        this.name = value;
    }


    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Override
    public String getDescription()
    {
        return description;
    }


    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Override
    public void setDescription(String value)
    {
        this.description = value;
    }


    /**
     * Gets the value of the author property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Override
    public String getAuthor()
    {
        return author;
    }


    /**
     * Sets the value of the author property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Override
    public void setAuthor(String value)
    {
        this.author = value;
    }


    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Override
    public String getVersion()
    {
        return version;
    }


    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Override
    public void setVersion(String value)
    {
        this.version = value;
    }


    /**
     * Gets the value of the keywords property.
     *
     * @return
     *     possible object is
     *     {@link Keywords }
     *
     */
    @Override
    public Keywords getKeywords()
    {
        return keywords;
    }


    /**
     * Sets the value of the keywords property.
     *
     * @param value
     *     allowed object is
     *     {@link Keywords }
     *
     */
    @Override
    public void setKeywords(Keywords value)
    {
        this.keywords = value;
    }


    /**
     * Gets the value of the settings property.
     *
     * @return
     *     possible object is
     *     {@link Settings }
     *
     */
    @Override
    public Settings getSettings()
    {
        return settings;
    }


    /**
     * Sets the value of the settings property.
     *
     * @param value
     *     allowed object is
     *     {@link Settings }
     *
     */
    @Override
    public void setSettings(Settings value)
    {
        this.settings = value;
    }


    /**
     * Gets the value of the defaultTitle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDefaultTitle()
    {
        return defaultTitle;
    }


    /**
     * Sets the value of the defaultTitle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDefaultTitle(String value)
    {
        this.defaultTitle = value;
    }


    /**
     * Gets the value of the view property.
     *
     * @return
     *     possible object is
     *     {@link View }
     *
     */
    public View getView()
    {
        return view;
    }


    /**
     * Sets the value of the view property.
     *
     * @param value
     *     allowed object is
     *     {@link View }
     *
     */
    public void setView(View value)
    {
        this.view = value;
    }


    /**
     * Gets the value of the controller property.
     *
     * @return
     *     possible object is
     *     {@link Controller }
     *
     */
    public Controller getController()
    {
        return controller;
    }


    /**
     * Sets the value of the controller property.
     *
     * @param value
     *     allowed object is
     *     {@link Controller }
     *
     */
    public void setController(Controller value)
    {
        this.controller = value;
    }


    /**
     * Gets the value of the sockets property.
     *
     * @return
     *     possible object is
     *     {@link Sockets }
     *
     */
    @Override
    public Sockets getSockets()
    {
        return sockets;
    }


    /**
     * Sets the value of the sockets property.
     *
     * @param value
     *     allowed object is
     *     {@link Sockets }
     *
     */
    @Override
    public void setSockets(Sockets value)
    {
        this.sockets = value;
    }
}
