/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.10.24 at 10:26:02 AM BST
//
package com.hybris.cockpitng.core.config.impl.jaxb.collectionbrowser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="available-molds" type="{http://www.hybris.com/cockpitng/config/collectionbrowser}mold-list" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="enable-multi-select" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
                {"availableMolds"})
@XmlRootElement(name = "collection-browser")
public class CollectionBrowser
{
    @XmlElement(name = "available-molds")
    protected MoldList availableMolds;
    @XmlAttribute(name = "enable-multi-select")
    protected Boolean enableMultiSelect;


    /**
     * Gets the value of the availableMolds property.
     * @return
     *          possible object is
     *         {@link MoldList }
     */
    public MoldList getAvailableMolds()
    {
        return availableMolds;
    }


    /**
     * Sets the value of the availableMolds property.
     * @param value
     *           allowed object is
     *           {@link MoldList }
     */
    public void setAvailableMolds(final MoldList value)
    {
        this.availableMolds = value;
    }


    /**
     * Gets the value of the enableMultiSelect property.
     * @return
     *          possible object is
     *         {@link Boolean }
     */
    public Boolean isEnableMultiSelect()
    {
        return enableMultiSelect;
    }


    /**
     * Sets the value of the enableMultiSelect property.
     * @param value
     *           allowed object is
     *           {@link Boolean }
     */
    public void setEnableMultiSelect(final Boolean value)
    {
        this.enableMultiSelect = value;
    }
}
