/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.09.02 at 02:26:13 PM CEST
//
package com.hybris.cockpitng.core.config.impl.jaxb.collectionbrowser;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for mold-list complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="mold-list"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mold" type="{http://www.hybris.com/cockpitng/config/collectionbrowser}mold" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="default-mold" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mold-list", propOrder = {
                "mold"
})
public class MoldList
{
    @XmlElement(required = true)
    protected List<Mold> mold;
    @XmlAttribute(name = "default-mold")
    protected String defaultMold;


    /**
     * Gets the value of the mold property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mold property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMold().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mold }
     *
     *
     */
    public List<Mold> getMold()
    {
        if(mold == null)
        {
            mold = new ArrayList<Mold>();
        }
        return this.mold;
    }


    /**
     * Gets the value of the defaultMold property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDefaultMold()
    {
        return defaultMold;
    }


    /**
     * Sets the value of the defaultMold property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDefaultMold(String value)
    {
        this.defaultMold = value;
    }
}
