/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.09.02 at 02:26:13 PM CEST
//
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hybris.com/cockpitng/config/collectionbrowser", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hybris.cockpitng.core.config.impl.jaxb.collectionbrowser;
