package de.hybris.platform.workflow.services.internal;

import de.hybris.platform.workflow.exceptions.AutomatedWorkflowTemplateException;
import de.hybris.platform.workflow.jobs.AutomatedWorkflowTemplateJob;
import de.hybris.platform.workflow.model.AutomatedWorkflowActionTemplateModel;

public interface AutomatedWorkflowTemplateRegistry
{
    AutomatedWorkflowTemplateJob getAutomatedWorkflowTemplateJobForTemplate(AutomatedWorkflowActionTemplateModel paramAutomatedWorkflowActionTemplateModel) throws AutomatedWorkflowTemplateException;
}
