package com.hybris.datahub.model;

public enum CanonicalItemPublicationStatusDetail
{
    INCOMPLETE, INVALID_REFERENCE_KEY, INCOMPLETE_REFERENCE_KEY, MISSING_REFERENCE, INTERNAL_MISSING_REFERENCE, ALREADY_IN_PROGRESS, EXCEPTION_SEE_LOG, PUBLICATION_FAILURE, NOT_PUBLISHED;
}
