/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.27 at 12:10:55 PM CET
//
package com.hybris.cockpitng.core.config.impl.jaxb.editorarea;

import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Positioned;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for abstractPositioned complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="abstractPositioned"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/common}positioned"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 * @deprecated since 6.3
 * @see com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Positioned
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstractPositioned", namespace = "http://www.hybris.com/cockpitng/component/editorArea")
@XmlSeeAlso({Attribute.class, AbstractPanel.class, AbstractTab.class, AbstractSection.class})
@Deprecated(since = "6.3", forRemoval = true)
public abstract class AbstractPositioned extends Positioned
{
}
