/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.08.06 at 11:03:43 AM CEST
//
package com.hybris.cockpitng.core.config.impl.jaxb.editorarea;

import com.hybris.cockpitng.core.config.impl.jaxb.listview.ListColumn;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for attribute complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="attribute"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/component/editorArea}abstractPositioned"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="editor-parameter" type="{http://www.hybris.com/cockpitng/component/editorArea}parameter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="column" type="{http://www.hybris.com/cockpitng/component/listView}list-column" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="qualifier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="readonly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="editor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="merge-mode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attribute", propOrder = {
                "editorParameter",
                "column"
})
public class Attribute
                extends AbstractPositioned
{
    @XmlElement(name = "editor-parameter")
    protected List<Parameter> editorParameter;
    protected List<ListColumn> column;
    @XmlAttribute(name = "qualifier", required = true)
    protected String qualifier;
    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "visible")
    protected Boolean visible;
    @XmlAttribute(name = "readonly")
    protected Boolean readonly;
    @XmlAttribute(name = "editor")
    protected String editor;
    @XmlAttribute(name = "merge-mode")
    protected String mergeMode;
    @XmlAttribute(name = "description")
    protected String description;


    /**
     * Gets the value of the editorParameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the editorParameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEditorParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     *
     *
     */
    public List<Parameter> getEditorParameter()
    {
        if(editorParameter == null)
        {
            editorParameter = new ArrayList<Parameter>();
        }
        return this.editorParameter;
    }


    /**
     * Gets the value of the qualifier property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getQualifier()
    {
        return qualifier;
    }


    /**
     * Sets the value of the qualifier property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setQualifier(String value)
    {
        this.qualifier = value;
    }


    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel()
    {
        return label;
    }


    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value)
    {
        this.label = value;
    }


    /**
     * Gets the value of the visible property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isVisible()
    {
        if(visible == null)
        {
            return true;
        }
        else
        {
            return visible;
        }
    }


    /**
     * Sets the value of the visible property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setVisible(Boolean value)
    {
        this.visible = value;
    }


    /**
     * Gets the value of the readonly property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isReadonly()
    {
        if(readonly == null)
        {
            return false;
        }
        else
        {
            return readonly;
        }
    }


    /**
     * Sets the value of the readonly property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setReadonly(Boolean value)
    {
        this.readonly = value;
    }


    /**
     * Gets the value of the editor property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEditor()
    {
        return editor;
    }


    /**
     * Sets the value of the editor property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEditor(String value)
    {
        this.editor = value;
    }


    /**
     * Gets the value of the mergeMode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMergeMode()
    {
        return mergeMode;
    }


    /**
     * Sets the value of the mergeMode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMergeMode(String value)
    {
        this.mergeMode = value;
    }


    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescription()
    {
        return description;
    }


    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescription(String value)
    {
        this.description = value;
    }
}
