/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.24 at 08:36:08 AM CET
//
package com.hybris.cockpitng.config.summaryview.jaxb;

import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Positioned;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for actions complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="actions"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/common}positioned"&gt;
 *       &lt;attribute name="component-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="group" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="renderer" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actions", namespace = "http://www.hybris.com/cockpitng/component/summaryview")
public class Actions extends Positioned
{
    @XmlAttribute(name = "component-id", required = true)
    protected String componentId;
    @XmlAttribute(name = "group")
    protected String group;
    @XmlAttribute(name = "renderer")
    protected String renderer;


    /**
     * Gets the value of the componentId property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getComponentId()
    {
        return componentId;
    }


    /**
     * Sets the value of the componentId property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setComponentId(String value)
    {
        this.componentId = value;
    }


    /**
     * Gets the value of the group property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getGroup()
    {
        return group;
    }


    /**
     * Sets the value of the group property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setGroup(String value)
    {
        this.group = value;
    }


    /**
     * Gets the value of the renderer property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getRenderer()
    {
        return renderer;
    }


    /**
     * Sets the value of the renderer property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setRenderer(String value)
    {
        this.renderer = value;
    }
}
