/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.24 at 08:36:08 AM CET
//
package com.hybris.cockpitng.config.summaryview.jaxb;

import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Positioned;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for attribute complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="attribute"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/common}positioned"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="editor-parameter" type="{http://www.hybris.com/cockpitng/component/summaryview}parameter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="qualifier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="editor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="merge-mode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attribute", namespace = "http://www.hybris.com/cockpitng/component/summaryview", propOrder = {
                "editorParameter"})
@XmlSeeAlso({CustomAttribute.class})
public class Attribute extends Positioned
{
    @XmlElement(name = "editor-parameter", namespace = "http://www.hybris.com/cockpitng/component/summaryview")
    protected List<Parameter> editorParameter;
    @XmlAttribute(name = "qualifier", required = true)
    protected String qualifier;
    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "visible")
    protected Boolean visible;
    @XmlAttribute(name = "editor")
    protected String editor;
    @XmlAttribute(name = "merge-mode")
    protected String mergeMode;


    /**
     * Gets the value of the editorParameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the editorParameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getEditorParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     *
     *
     */
    public List<Parameter> getEditorParameter()
    {
        if(editorParameter == null)
        {
            editorParameter = new ArrayList<Parameter>();
        }
        return this.editorParameter;
    }


    /**
     * Gets the value of the qualifier property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getQualifier()
    {
        return qualifier;
    }


    /**
     * Sets the value of the qualifier property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setQualifier(String value)
    {
        this.qualifier = value;
    }


    /**
     * Gets the value of the label property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getLabel()
    {
        return label;
    }


    /**
     * Sets the value of the label property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setLabel(String value)
    {
        this.label = value;
    }


    /**
     * Gets the value of the visible property.
     *
     * @return
     *            possible object is
     *         {@link Boolean }
     *
     */
    public boolean isVisible()
    {
        if(visible == null)
        {
            return true;
        }
        else
        {
            return visible;
        }
    }


    /**
     * Sets the value of the visible property.
     *
     * @param value
     *           allowed object is
     *           {@link Boolean }
     *
     */
    public void setVisible(Boolean value)
    {
        this.visible = value;
    }


    /**
     * Gets the value of the editor property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getEditor()
    {
        return editor;
    }


    /**
     * Sets the value of the editor property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setEditor(String value)
    {
        this.editor = value;
    }


    /**
     * Gets the value of the mergeMode property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getMergeMode()
    {
        return mergeMode;
    }


    /**
     * Sets the value of the mergeMode property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setMergeMode(String value)
    {
        this.mergeMode = value;
    }
}
