/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.24 at 08:36:08 AM CET
//
package com.hybris.cockpitng.config.summaryview.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for customSection complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="customSection"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/component/summaryview}section"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="render-parameter" type="{http://www.hybris.com/cockpitng/component/summaryview}parameter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="spring-bean" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customSection", namespace = "http://www.hybris.com/cockpitng/component/summaryview", propOrder = {
                "renderParameter"})
public class CustomSection extends Section
{
    @XmlElement(name = "render-parameter", namespace = "http://www.hybris.com/cockpitng/component/summaryview")
    protected List<Parameter> renderParameter;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute(name = "spring-bean")
    protected String springBean;


    /**
     * Gets the value of the renderParameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the renderParameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getRenderParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     *
     *
     */
    public List<Parameter> getRenderParameter()
    {
        if(renderParameter == null)
        {
            renderParameter = new ArrayList<Parameter>();
        }
        return this.renderParameter;
    }


    /**
     * Gets the value of the clazz property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getClazz()
    {
        return clazz;
    }


    /**
     * Sets the value of the clazz property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setClazz(String value)
    {
        this.clazz = value;
    }


    /**
     * Gets the value of the springBean property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getSpringBean()
    {
        return springBean;
    }


    /**
     * Sets the value of the springBean property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setSpringBean(String value)
    {
        this.springBean = value;
    }
}
