/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.24 at 08:36:08 AM CET
//
package com.hybris.cockpitng.config.summaryview.jaxb;

import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Positioned;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for dataQualityGroup complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="dataQualityGroup"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/common}positioned"&gt;
 *       &lt;attribute name="warning" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="error" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="domainId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataQualityGroup", namespace = "http://www.hybris.com/cockpitng/component/summaryview")
public class DataQualityGroup extends Positioned
{
    @XmlAttribute(name = "warning")
    protected Double warning;
    @XmlAttribute(name = "error")
    protected Double error;
    @XmlAttribute(name = "domain-id", required = true)
    protected String domainId;
    @XmlAttribute(name = "label")
    protected String label;


    /**
     * Gets the value of the warning property.
     *
     * @return
     *            possible object is
     *         {@link Double }
     *
     */
    public Double getWarning()
    {
        return warning;
    }


    /**
     * Sets the value of the warning property.
     *
     * @param value
     *           allowed object is
     *           {@link Double }
     *
     */
    public void setWarning(Double value)
    {
        this.warning = value;
    }


    /**
     * Gets the value of the error property.
     *
     * @return
     *            possible object is
     *         {@link Double }
     *
     */
    public Double getError()
    {
        return error;
    }


    /**
     * Sets the value of the error property.
     *
     * @param value
     *           allowed object is
     *           {@link Double }
     *
     */
    public void setError(Double value)
    {
        this.error = value;
    }


    /**
     * Gets the value of the domainId property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getDomainId()
    {
        return domainId;
    }


    /**
     * Sets the value of the domainId property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setDomainId(String value)
    {
        this.domainId = value;
    }


    /**
     * Gets the value of the label property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getLabel()
    {
        return label;
    }


    /**
     * Sets the value of the label property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setLabel(String value)
    {
        this.label = value;
    }
}
