/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.24 at 08:36:08 AM CET
//
package com.hybris.cockpitng.config.summaryview.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.hybris.cockpitng.config.summaryview.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory
{
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * com.hybris.cockpitng.config.summaryview.jaxb
     *
     */
    public ObjectFactory()
    {
    }


    /**
     * Create an instance of {@link SummaryView }
     *
     */
    public SummaryView createSummaryView()
    {
        return new SummaryView();
    }


    /**
     * Create an instance of {@link CustomSection }
     *
     */
    public CustomSection createCustomSection()
    {
        return new CustomSection();
    }


    /**
     * Create an instance of {@link Section }
     *
     */
    public Section createSection()
    {
        return new Section();
    }


    /**
     * Create an instance of {@link CustomAttribute }
     *
     */
    public CustomAttribute createCustomAttribute()
    {
        return new CustomAttribute();
    }


    /**
     * Create an instance of {@link Parameter }
     *
     */
    public Parameter createParameter()
    {
        return new Parameter();
    }


    /**
     * Create an instance of {@link Attribute }
     *
     */
    public Attribute createAttribute()
    {
        return new Attribute();
    }


    /**
     * Create an instance of {@link Actions }
     *
     */
    public Actions createActions()
    {
        return new Actions();
    }


    /**
     * Create an instance of {@link DataQualityGroup }
     *
     */
    public DataQualityGroup createDataQualityGroup()
    {
        return new DataQualityGroup();
    }
}
