/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.24 at 08:36:08 AM CET
//
package com.hybris.cockpitng.config.summaryview.jaxb;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Positioned;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for section complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="section"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/component/summaryview}abstractSection"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="custom-attribute" type="{http://www.hybris.com/cockpitng/component/summaryview}customAttribute"/&gt;
 *           &lt;element name="attribute" type="{http://www.hybris.com/cockpitng/component/summaryview}attribute"/&gt;
 *           &lt;element name="actions" type="{http://www.hybris.com/cockpitng/component/summaryview}actions"/&gt;
 *           &lt;element name="data-quality-group" type="{http://www.hybris.com/cockpitng/component/summaryview}dataQualityGroup"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "section", namespace = "http://www.hybris.com/cockpitng/component/summaryview", propOrder = {
                "customAttributeOrAttributeOrActions"})
@XmlSeeAlso({CustomSection.class})
public class Section extends AbstractSection
{
    @Mergeable(key = {"qualifier", "domainId", "componentId", "group", "springBean"})
    @XmlElements({
                    @XmlElement(name = "custom-attribute", namespace = "http://www.hybris.com/cockpitng/component/summaryview", type = CustomAttribute.class),
                    @XmlElement(name = "attribute", namespace = "http://www.hybris.com/cockpitng/component/summaryview", type = Attribute.class),
                    @XmlElement(name = "actions", namespace = "http://www.hybris.com/cockpitng/component/summaryview", type = Actions.class),
                    @XmlElement(name = "data-quality-group", namespace = "http://www.hybris.com/cockpitng/component/summaryview", type = DataQualityGroup.class)})
    protected List<Positioned> customAttributeOrAttributeOrActions;


    /**
     * Gets the value of the customAttributeOrAttributeOrActions property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customAttributeOrAttributeOrActions property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getCustomAttributeOrAttributeOrActions().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomAttribute }
     * {@link Attribute }
     * {@link Actions }
     * {@link DataQualityGroup }
     *
     *
     */
    public List<Positioned> getCustomAttributeOrAttributeOrActions()
    {
        if(customAttributeOrAttributeOrActions == null)
        {
            customAttributeOrAttributeOrActions = new ArrayList<Positioned>();
        }
        return this.customAttributeOrAttributeOrActions;
    }
}
