/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 01:11:24 PM CEST 
//
package com.hybris.cockpitng.config.summaryview.jaxb;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.ImagePreview;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/common}image-preview"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="custom-section" type="{http://www.hybris.com/cockpitng/component/summaryview}customSection"/&gt;
 *           &lt;element name="section" type="{http://www.hybris.com/cockpitng/component/summaryview}section"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="display-title" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
                "customSectionOrSection"
})
@XmlRootElement(name = "summary-view")
public class SummaryView extends ImagePreview
{
    @Mergeable(key = "name")
    @XmlElements({
                    @XmlElement(name = "custom-section", type = CustomSection.class),
                    @XmlElement(name = "section")
    })
    protected List<Section> customSectionOrSection;
    @XmlAttribute(name = "display-title")
    protected Boolean displayTitle;


    /**
     * Gets the value of the customSectionOrSection property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customSectionOrSection property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomSectionOrSection().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomSection }
     * {@link Section }
     *
     *
     */
    public List<Section> getCustomSectionOrSection()
    {
        if(customSectionOrSection == null)
        {
            customSectionOrSection = new ArrayList<Section>();
        }
        return this.customSectionOrSection;
    }


    /**
     * Gets the value of the displayTitle property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isDisplayTitle()
    {
        if(displayTitle == null)
        {
            return true;
        }
        else
        {
            return displayTitle;
        }
    }


    /**
     * Sets the value of the displayTitle property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDisplayTitle(Boolean value)
    {
        this.displayTitle = value;
    }
}
