/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 08:49:51 AM CET 
//
package com.hybris.cockpitng.config.fulltextsearch.jaxb;

import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Positioned;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for FieldType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FieldType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/common}positioned"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="editor-parameter" type="{http://www.hybris.com/cockpitng/config/fulltextsearch}Parameter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="selected" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="editor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="merge-mode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FieldType", propOrder =
                {"editorParameter"})
public class FieldType extends Positioned
{
    @XmlElement(name = "editor-parameter")
    protected List<Parameter> editorParameter;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "displayName")
    protected String displayName;
    @XmlAttribute(name = "selected")
    protected Boolean selected;
    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "editor")
    protected String editor;
    @XmlAttribute(name = "merge-mode")
    protected String mergeMode;


    /**
     * Gets the value of the editorParameter property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the editorParameter property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getEditorParameter().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Parameter }
     */
    public List<Parameter> getEditorParameter()
    {
        if(editorParameter == null)
        {
            editorParameter = new ArrayList<Parameter>();
        }
        return this.editorParameter;
    }


    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     */
    public String getName()
    {
        return name;
    }


    /**
     * Sets the value of the name property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setName(String value)
    {
        this.name = value;
    }


    /**
     * Gets the value of the displayName property.
     *
     * @return possible object is {@link String }
     */
    public String getDisplayName()
    {
        return displayName;
    }


    /**
     * Sets the value of the displayName property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setDisplayName(String value)
    {
        this.displayName = value;
    }


    /**
     * Gets the value of the selected property.
     *
     * @return possible object is {@link Boolean }
     */
    public boolean isSelected()
    {
        if(selected == null)
        {
            return false;
        }
        else
        {
            return selected;
        }
    }


    /**
     * Sets the value of the selected property.
     *
     * @param value
     *           allowed object is {@link Boolean }
     */
    public void setSelected(Boolean value)
    {
        this.selected = value;
    }


    /**
     * Gets the value of the label property.
     *
     * @return possible object is {@link String }
     */
    public String getLabel()
    {
        return label;
    }


    /**
     * Sets the value of the label property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setLabel(String value)
    {
        this.label = value;
    }


    /**
     * Gets the value of the editor property.
     *
     * @return possible object is {@link String }
     */
    public String getEditor()
    {
        return editor;
    }


    /**
     * Sets the value of the editor property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setEditor(String value)
    {
        this.editor = value;
    }


    /**
     * Gets the value of the mergeMode property.
     *
     * @return possible object is {@link String }
     */
    public String getMergeMode()
    {
        return mergeMode;
    }


    /**
     * Sets the value of the mergeMode property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setMergeMode(String value)
    {
        this.mergeMode = value;
    }
}
