/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.22 at 08:42:04 AM CET 
//
package com.hybris.cockpitng.config.fulltextsearch.jaxb;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="field-list" type="{http://www.hybris.com/cockpitng/config/fulltextsearch}FieldListType"/&gt;
 *         &lt;element name="preferred-search-strategy" type="{http://www.w3.org/2001/XMLSchema}string" default="" /&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
                {"fieldList", "preferredSearchStrategy", "operator"})
@XmlRootElement(name = "fulltext-search")
public class FulltextSearch
{
    @XmlElement(name = "field-list", required = true)
    @Mergeable(key = {})
    protected FieldListType fieldList;
    @XmlElement(name = "preferred-search-strategy")
    protected String preferredSearchStrategy;
    @XmlElement(name = "operator", defaultValue = "AND")
    protected OperatorType operator;


    /**
     * Gets the value of the fieldList property.
     *
     * @return possible object is {@link FieldListType }
     */
    public FieldListType getFieldList()
    {
        return fieldList;
    }


    /**
     * Sets the value of the fieldList property.
     *
     * @param value
     *           allowed object is {@link FieldListType }
     */
    public void setFieldList(FieldListType value)
    {
        this.fieldList = value;
    }


    /**
     * Gets the value of the preferredSearchStrategy property.
     *
     * @return possible object is {@link String }
     */
    public String getPreferredSearchStrategy()
    {
        if(preferredSearchStrategy == null)
        {
            return "";
        }
        else
        {
            return preferredSearchStrategy;
        }
    }


    /**
     * Sets the value of the preferredSearchStrategy property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setPreferredSearchStrategy(String value)
    {
        this.preferredSearchStrategy = value;
    }


    /**
     * Gets the value of the operator property.
     *
     * @return possible object is {@link OperatorType }
     */
    public OperatorType getOperator()
    {
        if(operator == null)
        {
            return OperatorType.AND;
        }
        else
        {
            return operator;
        }
    }


    /**
     * Sets the value of the operator property.
     *
     * @param value
     *           allowed object is {@link OperatorType }
     */
    public void setOperator(OperatorType value)
    {
        this.operator = value;
    }
}
