/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:03:23 PM CEST 
//
package com.hybris.cockpitng.config.compareview.jaxb;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.MergeMode;
import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Parameter;
import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Positioned;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for attribute complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="attribute"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/common}positioned"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="parameter" type="{http://www.hybris.com/cockpitng/config/common}parameter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="merge-mode" type="{http://www.hybris.com/cockpitng/config/common}MergeMode" default="MERGE" /&gt;
 *       &lt;attribute name="qualifier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="readonly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="renderer" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="editor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attribute", propOrder =
                {"parameter"})
public class Attribute extends Positioned
{
    @Mergeable(key = "name")
    protected List<Parameter> parameter;
    @XmlAttribute(name = "merge-mode")
    protected MergeMode mergeMode;
    @XmlAttribute(name = "qualifier", required = true)
    protected String qualifier;
    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "readonly")
    protected Boolean readonly;
    @XmlAttribute(name = "renderer")
    protected String renderer;
    @XmlAttribute(name = "editor")
    protected String editor;


    /**
     * Gets the value of the parameter property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * parameter property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getParameter().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Parameter }
     */
    public List<Parameter> getParameter()
    {
        if(parameter == null)
        {
            parameter = new ArrayList<Parameter>();
        }
        return this.parameter;
    }


    /**
     * Gets the value of the mergeMode property.
     *
     * @return possible object is {@link MergeMode }
     */
    public MergeMode getMergeMode()
    {
        return mergeMode;
    }


    /**
     * Sets the value of the mergeMode property.
     *
     * @param value
     *           allowed object is {@link MergeMode }
     */
    public void setMergeMode(MergeMode value)
    {
        this.mergeMode = value;
    }


    /**
     * Gets the value of the qualifier property.
     *
     * @return possible object is {@link String }
     */
    public String getQualifier()
    {
        return qualifier;
    }


    /**
     * Sets the value of the qualifier property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setQualifier(String value)
    {
        this.qualifier = value;
    }


    /**
     * Gets the value of the label property.
     *
     * @return possible object is {@link String }
     */
    public String getLabel()
    {
        return label;
    }


    /**
     * Sets the value of the label property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setLabel(String value)
    {
        this.label = value;
    }


    /**
     * Gets the value of the readonly property.
     *
     * @return possible object is {@link Boolean }
     */
    public boolean isReadonly()
    {
        if(readonly == null)
        {
            return false;
        }
        else
        {
            return readonly;
        }
    }


    /**
     * Sets the value of the readonly property.
     *
     * @param value
     *           allowed object is {@link Boolean }
     */
    public void setReadonly(Boolean value)
    {
        this.readonly = value;
    }


    /**
     * Gets the value of the renderer property.
     *
     * @return possible object is {@link String }
     */
    public String getRenderer()
    {
        return renderer;
    }


    /**
     * Sets the value of the renderer property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setRenderer(String value)
    {
        this.renderer = value;
    }


    /**
     * Gets the value of the editor property.
     *
     * @return possible object is {@link String }
     */
    public String getEditor()
    {
        return editor;
    }


    /**
     * Sets the value of the editor property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setEditor(String value)
    {
        this.editor = value;
    }
}
