/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 10:31:28 AM CEST 
//
package com.hybris.cockpitng.config.compareview.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for grid-view-ctx complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="grid-view-ctx"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="ctx" type="{http://www.w3.org/2001/XMLSchema}string" default="grid-view" /&gt;
 *       &lt;attribute name="use" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grid-view-ctx")
public class GridViewCtx
{
    @XmlAttribute(name = "ctx")
    protected String ctx;
    @XmlAttribute(name = "use")
    protected Boolean use;


    /**
     * Gets the value of the ctx property.
     *
     * @return possible object is {@link String }
     */
    public String getCtx()
    {
        if(ctx == null)
        {
            return "grid-view";
        }
        else
        {
            return ctx;
        }
    }


    /**
     * Sets the value of the ctx property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setCtx(String value)
    {
        this.ctx = value;
    }


    /**
     * Gets the value of the use property.
     *
     * @return possible object is {@link Boolean }
     */
    public boolean isUse()
    {
        if(use == null)
        {
            return true;
        }
        else
        {
            return use;
        }
    }


    /**
     * Sets the value of the use property.
     *
     * @param value
     *           allowed object is {@link Boolean }
     */
    public void setUse(Boolean value)
    {
        this.use = value;
    }
}
