/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 10:31:28 AM CEST 
//
package com.hybris.cockpitng.config.compareview.jaxb;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.ImagePreview;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for header complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="header"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hybris.com/cockpitng/config/common}image-preview"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="additional-renderer" type="{http://www.hybris.com/cockpitng/component/compareview}renderer" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "header", propOrder =
                {"additionalRenderer"})
public class Header extends ImagePreview
{
    @Mergeable(key = "springBean", mergeModeProperty = "mergeMode")
    @XmlElement(name = "additional-renderer")
    protected List<Renderer> additionalRenderer;


    /**
     * Gets the value of the additionalRenderer property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * additionalRenderer property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getAdditionalRenderer().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Renderer }
     */
    public List<Renderer> getAdditionalRenderer()
    {
        if(additionalRenderer == null)
        {
            additionalRenderer = new ArrayList<Renderer>();
        }
        return this.additionalRenderer;
    }
}
