/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:03:23 PM CEST 
//
package com.hybris.cockpitng.config.compareview.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.hybris.cockpitng.config.compareview.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 */
@XmlRegistry
public class ObjectFactory
{
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * com.hybris.cockpitng.config.compareview.jaxb
     */
    public ObjectFactory()
    {
    }


    /**
     * Create an instance of {@link CompareView }
     */
    public CompareView createCompareView()
    {
        return new CompareView();
    }


    /**
     * Create an instance of {@link EditorAreaCtx }
     */
    public EditorAreaCtx createEditorAreaCtx()
    {
        return new EditorAreaCtx();
    }


    /**
     * Create an instance of {@link GridViewCtx }
     */
    public GridViewCtx createGridViewCtx()
    {
        return new GridViewCtx();
    }


    /**
     * Create an instance of {@link Header }
     */
    public Header createHeader()
    {
        return new Header();
    }


    /**
     * Create an instance of {@link Section }
     */
    public Section createSection()
    {
        return new Section();
    }


    /**
     * Create an instance of {@link Renderer }
     */
    public Renderer createRenderer()
    {
        return new Renderer();
    }


    /**
     * Create an instance of {@link Attribute }
     */
    public Attribute createAttribute()
    {
        return new Attribute();
    }
}
