/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:03:23 PM CEST 
//
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hybris.com/cockpitng/component/compareview", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hybris.cockpitng.config.compareview.jaxb;
