/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 10:31:28 AM CEST 
//
package com.hybris.cockpitng.config.compareview.jaxb;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.MergeMode;
import com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig.Positioned;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for section complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="section"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="attribute" type="{http://www.hybris.com/cockpitng/component/compareview}attribute" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="merge-mode" type="{http://www.hybris.com/cockpitng/config/common}MergeMode" default="MERGE" /&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="tooltipText" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="renderer" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="initiallyOpened" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "section", propOrder =
                {"attribute"})
public class Section extends Positioned
{
    @Mergeable(key = "qualifier", mergeModeProperty = "mergeMode")
    @XmlElement(required = true)
    protected List<Attribute> attribute;
    @XmlAttribute(name = "merge-mode")
    protected MergeMode mergeMode;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "tooltipText")
    protected String tooltipText;
    @XmlAttribute(name = "renderer")
    protected String renderer;
    @XmlAttribute(name = "initiallyOpened")
    protected Boolean initiallyOpened;


    /**
     * Gets the value of the attribute property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * attribute property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getAttribute().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Attribute }
     */
    public List<Attribute> getAttribute()
    {
        if(attribute == null)
        {
            attribute = new ArrayList<>();
        }
        return this.attribute;
    }


    /**
     * Gets the value of the mergeMode property.
     *
     * @return possible object is {@link MergeMode }
     */
    public MergeMode getMergeMode()
    {
        return mergeMode;
    }


    /**
     * Sets the value of the mergeMode property.
     *
     * @param value
     *           allowed object is {@link MergeMode }
     */
    public void setMergeMode(MergeMode value)
    {
        this.mergeMode = value;
    }


    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     */
    public String getName()
    {
        return name;
    }


    /**
     * Sets the value of the name property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setName(String value)
    {
        this.name = value;
    }


    /**
     * Gets the value of the tooltipText property.
     *
     * @return possible object is {@link String }
     */
    public String getTooltipText()
    {
        return tooltipText;
    }


    /**
     * Sets the value of the tooltipText property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setTooltipText(String value)
    {
        this.tooltipText = value;
    }


    /**
     * Gets the value of the renderer property.
     *
     * @return possible object is {@link String }
     */
    public String getRenderer()
    {
        return renderer;
    }


    /**
     * Sets the value of the renderer property.
     *
     * @param value
     *           allowed object is {@link String }
     */
    public void setRenderer(String value)
    {
        this.renderer = value;
    }


    /**
     * Gets the value of the initiallyOpened property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isInitiallyOpened()
    {
        if(initiallyOpened == null)
        {
            return false;
        }
        else
        {
            return initiallyOpened;
        }
    }


    /**
     * Sets the value of the initiallyOpened property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setInitiallyOpened(Boolean value)
    {
        this.initiallyOpened = value;
    }
}
