/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 09:08:10 AM CEST 
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for AccessSettings complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AccessSettings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="add" type="{}AddAccess" minOccurs="0"/&gt;
 *         &lt;element name="remove" type="{}RemoveAccess" minOccurs="0"/&gt;
 *         &lt;element name="replace" type="{}ReplaceAccess" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessSettings", propOrder = {
                "add",
                "remove",
                "replace"
})
public class AccessSettings
{
    protected AddAccess add;
    protected RemoveAccess remove;
    protected ReplaceAccess replace;


    /**
     * Gets the value of the add property.
     *
     * @return
     *     possible object is
     *     {@link AddAccess }
     *
     */
    public AddAccess getAdd()
    {
        return add;
    }


    /**
     * Sets the value of the add property.
     *
     * @param value
     *     allowed object is
     *     {@link AddAccess }
     *
     */
    public void setAdd(AddAccess value)
    {
        this.add = value;
    }


    /**
     * Gets the value of the remove property.
     *
     * @return
     *     possible object is
     *     {@link RemoveAccess }
     *
     */
    public RemoveAccess getRemove()
    {
        return remove;
    }


    /**
     * Sets the value of the remove property.
     *
     * @param value
     *     allowed object is
     *     {@link RemoveAccess }
     *
     */
    public void setRemove(RemoveAccess value)
    {
        this.remove = value;
    }


    /**
     * Gets the value of the replace property.
     *
     * @return
     *     possible object is
     *     {@link ReplaceAccess }
     *
     */
    public ReplaceAccess getReplace()
    {
        return replace;
    }


    /**
     * Sets the value of the replace property.
     *
     * @param value
     *     allowed object is
     *     {@link ReplaceAccess }
     *
     */
    public void setReplace(ReplaceAccess value)
    {
        this.replace = value;
    }
}
