/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.29 at 05:49:40 PM MESZ
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AutoCreateMode.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="AutoCreateMode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DISABLED"/&gt;
 *     &lt;enumeration value="CREATE_IF_NO_INSTANCE_EXISTING"/&gt;
 *     &lt;enumeration value="CREATE_IF_RESOLVING_FAILED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "AutoCreateMode")
@XmlEnum
public enum AutoCreateMode
{
    DISABLED, CREATE_IF_NO_INSTANCE_EXISTING, CREATE_IF_RESOLVING_FAILED;


    public String value()
    {
        return name();
    }


    public static AutoCreateMode fromValue(final String value)
    {
        return valueOf(value);
    }
}
