/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.28 at 12:10:13 PM MESZ
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ExtensionModeType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="ExtensionModeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="append"/&gt;
 *     &lt;enumeration value="replace"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "ExtensionModeType")
@XmlEnum
public enum ExtensionModeType
{
    @XmlEnumValue("append")
    APPEND("append"), @XmlEnumValue("replace")
REPLACE("replace");
    private final String value;


    ExtensionModeType(final String value)
    {
        this.value = value;
    }


    public String value()
    {
        return value;
    }


    public static ExtensionModeType fromValue(final String fromValue)
    {
        for(final ExtensionModeType c : ExtensionModeType.values())
        {
            if(c.value.equals(fromValue))
            {
                return c;
            }
        }
        throw new IllegalArgumentException(fromValue);
    }
}
