/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.07.20 at 11:59:49 AM EDT
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for InstanceSettings complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="InstanceSettings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="create" type="{}CreateSettings" minOccurs="0"/&gt;
 *         &lt;element name="close" type="{}CloseSettings" minOccurs="0"/&gt;
 *         &lt;element name="select" type="{}SelectSettings" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="socketEventRoutingMode" type="{}SocketEventRoutingMode" default="LAST_USED" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstanceSettings", propOrder = {"create", "close", "select"})
public class InstanceSettings
{
    protected CreateSettings create;
    protected CloseSettings close;
    protected SelectSettings select;
    @XmlAttribute(name = "socketEventRoutingMode")
    protected SocketEventRoutingMode socketEventRoutingMode;


    /**
     * Gets the value of the create property.
     *
     * @return
     *         possible object is {@link CreateSettings }
     *
     */
    public CreateSettings getCreate()
    {
        return create;
    }


    /**
     * Sets the value of the create property.
     *
     * @param value
     *           allowed object is {@link CreateSettings }
     *
     */
    public void setCreate(final CreateSettings value)
    {
        this.create = value;
    }


    /**
     * Gets the value of the close property.
     *
     * @return
     *         possible object is {@link CloseSettings }
     *
     */
    public CloseSettings getClose()
    {
        return close;
    }


    /**
     * Sets the value of the close property.
     *
     * @param value
     *           allowed object is {@link CloseSettings }
     *
     */
    public void setClose(final CloseSettings value)
    {
        this.close = value;
    }


    /**
     * Gets the value of the select property.
     *
     * @return
     *         possible object is {@link SelectSettings }
     *
     */
    public SelectSettings getSelect()
    {
        return select;
    }


    /**
     * Sets the value of the select property.
     *
     * @param value
     *           allowed object is {@link SelectSettings }
     *
     */
    public void setSelect(final SelectSettings value)
    {
        this.select = value;
    }


    /**
     * Gets the value of the socketEventRoutingMode property.
     *
     * @return
     *         possible object is {@link SocketEventRoutingMode }
     *
     */
    public SocketEventRoutingMode getSocketEventRoutingMode()
    {
        if(socketEventRoutingMode == null)
        {
            return SocketEventRoutingMode.LAST_USED;
        }
        else
        {
            return socketEventRoutingMode;
        }
    }


    /**
     * Sets the value of the socketEventRoutingMode property.
     *
     * @param value
     *           allowed object is {@link SocketEventRoutingMode }
     *
     */
    public void setSocketEventRoutingMode(final SocketEventRoutingMode value)
    {
        this.socketEventRoutingMode = value;
    }
}
