/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.07.20 at 11:59:49 AM EDT
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SelectSettings complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SelectSettings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="incoming-events" type="{}SocketEvents" minOccurs="0"/&gt;
 *         &lt;element name="all-incoming-events" type="{}AllSocketEvents" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="onInit" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectSettings", propOrder = {"incomingEvents", "allIncomingEvents"})
public class SelectSettings
{
    @XmlElement(name = "incoming-events")
    protected SocketEvents incomingEvents;
    @XmlElement(name = "all-incoming-events")
    protected AllSocketEvents allIncomingEvents;
    @XmlAttribute(name = "onInit")
    protected Boolean onInit;


    /**
     * Gets the value of the incomingEvents property.
     *
     * @return
     *         possible object is {@link SocketEvents }
     *
     */
    public SocketEvents getIncomingEvents()
    {
        return incomingEvents;
    }


    /**
     * Sets the value of the incomingEvents property.
     *
     * @param value
     *           allowed object is {@link SocketEvents }
     *
     */
    public void setIncomingEvents(final SocketEvents value)
    {
        this.incomingEvents = value;
    }


    /**
     * Gets the value of the allIncomingEvents property.
     *
     * @return
     *         possible object is {@link AllSocketEvents }
     *
     */
    public AllSocketEvents getAllIncomingEvents()
    {
        return allIncomingEvents;
    }


    /**
     * Sets the value of the allIncomingEvents property.
     *
     * @param value
     *           allowed object is {@link AllSocketEvents }
     *
     */
    public void setAllIncomingEvents(final AllSocketEvents value)
    {
        this.allIncomingEvents = value;
    }


    /**
     * Gets the value of the onInit property.
     *
     * @return
     *         possible object is {@link Boolean }
     *
     */
    public boolean isOnInit()
    {
        if(onInit == null)
        {
            return false;
        }
        else
        {
            return onInit;
        }
    }


    /**
     * Sets the value of the onInit property.
     *
     * @param value
     *           allowed object is {@link Boolean }
     *
     */
    public void setOnInit(final Boolean value)
    {
        this.onInit = value;
    }
}
