/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.29 at 05:49:40 PM MESZ
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SettingType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="SettingType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="String"/&gt;
 *     &lt;enumeration value="Boolean"/&gt;
 *     &lt;enumeration value="Integer"/&gt;
 *     &lt;enumeration value="Double"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "SettingType")
@XmlEnum
public enum SettingType
{
    @XmlEnumValue("String")
    STRING("String"), @XmlEnumValue("Boolean")
BOOLEAN("Boolean"), @XmlEnumValue("Integer")
INTEGER("Integer"), @XmlEnumValue("Double")
DOUBLE("Double");
    private final String value;


    SettingType(final String value)
    {
        this.value = value;
    }


    public String value()
    {
        return value;
    }


    public static SettingType fromValue(final String fromVal)
    {
        for(final SettingType c : SettingType.values())
        {
            if(c.value.equals(fromVal))
            {
                return c;
            }
        }
        throw new IllegalArgumentException(fromVal);
    }
}
