/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.07.20 at 11:59:49 AM EDT
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SocketEventRoutingMode.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="SocketEventRoutingMode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SELECTED"/&gt;
 *     &lt;enumeration value="LAST_USED"/&gt;
 *     &lt;enumeration value="FIRST"/&gt;
 *     &lt;enumeration value="LAST"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "SocketEventRoutingMode")
@XmlEnum
public enum SocketEventRoutingMode
{
    SELECTED, LAST_USED, FIRST, LAST;


    public String value()
    {
        return name();
    }


    public static SocketEventRoutingMode fromValue(final String v)
    {
        return valueOf(v);
    }
}
