/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.15 at 11:02:34 AM CET 
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Removes a connection between two widgets.
 *
 * <p>Java class for WidgetConnectionRemove complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="WidgetConnectionRemove"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sourceWidgetId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="outputId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="targetWidgetId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="inputId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WidgetConnectionRemove")
public class WidgetConnectionRemove
{
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "sourceWidgetId")
    protected String sourceWidgetId;
    @XmlAttribute(name = "outputId")
    protected String outputId;
    @XmlAttribute(name = "targetWidgetId")
    protected String targetWidgetId;
    @XmlAttribute(name = "inputId")
    protected String inputId;


    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName()
    {
        return name;
    }


    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(final String value)
    {
        this.name = value;
    }


    /**
     * Gets the value of the sourceWidgetId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSourceWidgetId()
    {
        return sourceWidgetId;
    }


    /**
     * Sets the value of the sourceWidgetId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSourceWidgetId(final String value)
    {
        this.sourceWidgetId = value;
    }


    /**
     * Gets the value of the outputId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOutputId()
    {
        return outputId;
    }


    /**
     * Sets the value of the outputId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOutputId(final String value)
    {
        this.outputId = value;
    }


    /**
     * Gets the value of the targetWidgetId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTargetWidgetId()
    {
        return targetWidgetId;
    }


    /**
     * Sets the value of the targetWidgetId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTargetWidgetId(final String value)
    {
        this.targetWidgetId = value;
    }


    /**
     * Gets the value of the inputId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInputId()
    {
        return inputId;
    }


    /**
     * Sets the value of the inputId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInputId(final String value)
    {
        this.inputId = value;
    }
}
