/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.05.13 at 01:09:43 PM CEST
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Specifies widget to be moved to as a child (by ID).
 *
 * <p>
 * Java class for WidgetMove complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="WidgetMove"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="widgetId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="targetWidgetId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="targetSlotId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="failOnError" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WidgetMove")
public class WidgetMove
{
    @XmlAttribute(name = "widgetId", required = true)
    protected String widgetId;
    @XmlAttribute(name = "targetWidgetId", required = true)
    protected String targetWidgetId;
    @XmlAttribute(name = "targetSlotId", required = true)
    protected String targetSlotId;
    @XmlAttribute(name = "position")
    protected Integer position;
    @XmlAttribute(name = "failOnError")
    protected Boolean failOnError;


    /**
     * Gets the value of the widgetId property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getWidgetId()
    {
        return widgetId;
    }


    /**
     * Sets the value of the widgetId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setWidgetId(final String value)
    {
        this.widgetId = value;
    }


    /**
     * Gets the value of the targetWidgetId property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getTargetWidgetId()
    {
        return targetWidgetId;
    }


    /**
     * Sets the value of the targetWidgetId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setTargetWidgetId(final String value)
    {
        this.targetWidgetId = value;
    }


    /**
     * Gets the value of the targetSlotId property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getTargetSlotId()
    {
        return targetSlotId;
    }


    /**
     * Sets the value of the targetSlotId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setTargetSlotId(final String value)
    {
        this.targetSlotId = value;
    }


    /**
     * Gets the value of the position property.
     *
     * @return
     *         possible object is {@link Integer }
     *
     */
    public Integer getPosition()
    {
        return position;
    }


    /**
     * Sets the value of the position property.
     *
     * @param value
     *           allowed object is {@link Integer }
     *
     */
    public void setPosition(final Integer value)
    {
        this.position = value;
    }


    /**
     * Gets the value of the failOnError property.
     *
     * @return
     *         possible object is {@link Boolean }
     *
     */
    public boolean isFailOnError()
    {
        if(failOnError == null)
        {
            return false;
        }
        else
        {
            return failOnError;
        }
    }


    /**
     * Sets the value of the failOnError property.
     *
     * @param value
     *           allowed object is {@link Boolean }
     *
     */
    public void setFailOnError(final Boolean value)
    {
        this.failOnError = value;
    }
}
