/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.29 at 05:49:40 PM MESZ
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="widget" type="{}Widget" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="widget-connection" type="{}WidgetConnection" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="widget-extension" type="{}WidgetExtension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"requires", "widget", "widgetConnection", "widgetConnectionRemove", "widgetExtension", "imports"})
@XmlRootElement(name = "widgets")
public class Widgets
{
    @XmlElement(nillable = true)
    protected List<Widget> widget;
    @XmlElement(name = "widget-connection", nillable = true)
    protected List<WidgetConnection> widgetConnection;
    @XmlElement(name = "widget-connection-remove", nillable = true)
    protected List<WidgetConnectionRemove> widgetConnectionRemove;
    @XmlElement(name = "widget-extension", nillable = true)
    protected List<WidgetExtension> widgetExtension;
    @XmlElement(nillable = true, name = "import")
    private List<Import> imports;
    @XmlElement(nillable = true, name = "requires")
    private List<Requirement> requires;
    @XmlAttribute
    private String parameters;
    @XmlAttribute(name = "required-parameters")
    private String requiredParameters;


    /**
     * Gets the value of the widget property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the widget property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getWidget().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Widget }
     *
     *
     */
    @Mergeable(key = "id")
    public List<Widget> getWidget()
    {
        if(widget == null)
        {
            widget = new ArrayList<>();
        }
        return this.widget;
    }


    /**
     * Gets the value of the widgetConnection property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the widgetConnection property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getWidgetConnection().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link WidgetConnection }
     *
     *
     */
    public List<WidgetConnection> getWidgetConnection()
    {
        if(widgetConnection == null)
        {
            widgetConnection = new ArrayList<>();
        }
        return this.widgetConnection;
    }


    /**
     * Gets the value of the widgetExtension property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the widgetExtension property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getWidgetExtension().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link WidgetExtension }
     *
     *
     */
    public List<WidgetExtension> getWidgetExtension()
    {
        if(widgetExtension == null)
        {
            widgetExtension = new ArrayList<>();
        }
        return this.widgetExtension;
    }


    public List<Import> getImports()
    {
        if(imports == null)
        {
            imports = new ArrayList<>();
        }
        return imports;
    }


    public List<Requirement> getRequires()
    {
        if(requires == null)
        {
            requires = new ArrayList<Requirement>();
        }
        return requires;
    }


    public String getParameters()
    {
        return parameters;
    }


    public void setParameters(final String parameters)
    {
        this.parameters = parameters;
    }


    public String getRequiredParameters()
    {
        return requiredParameters;
    }


    public void setRequiredParameters(final String requiredParameters)
    {
        this.requiredParameters = requiredParameters;
    }


    /**
     * Gets the value of the widgetConnectionRemove property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the widgetConnectionRemove property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWidgetConnectionRemove().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WidgetConnectionRemove }
     *
     *
     */
    public List<WidgetConnectionRemove> getWidgetConnectionRemove()
    {
        if(widgetConnectionRemove == null)
        {
            widgetConnectionRemove = new ArrayList<WidgetConnectionRemove>();
        }
        return this.widgetConnectionRemove;
    }
}
