/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.29 at 05:49:40 PM MESZ
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WidgetConnection complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="WidgetConnection"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sourceWidgetId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="outputId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="targetWidgetId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="inputId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WidgetConnection")
public class WidgetConnection
{
    @XmlAttribute
    protected String name;
    @XmlAttribute(required = true)
    protected String sourceWidgetId;
    @XmlAttribute(required = true)
    protected String outputId;
    @XmlAttribute(required = true)
    protected String targetWidgetId;
    @XmlAttribute(required = true)
    protected String inputId;
    @XmlAttribute
    protected String moduleUrl;


    /**
     * Gets the value of the name property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getName()
    {
        return name;
    }


    /**
     * Sets the value of the name property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setName(final String value)
    {
        this.name = value;
    }


    /**
     * Gets the value of the sourceWidgetId property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getSourceWidgetId()
    {
        return sourceWidgetId;
    }


    /**
     * Sets the value of the sourceWidgetId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setSourceWidgetId(final String value)
    {
        this.sourceWidgetId = value;
    }


    /**
     * Gets the value of the outputId property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getOutputId()
    {
        return outputId;
    }


    /**
     * Sets the value of the outputId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setOutputId(final String value)
    {
        this.outputId = value;
    }


    /**
     * Gets the value of the targetWidgetId property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getTargetWidgetId()
    {
        return targetWidgetId;
    }


    /**
     * Sets the value of the targetWidgetId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setTargetWidgetId(final String value)
    {
        this.targetWidgetId = value;
    }


    /**
     * Gets the value of the inputId property.
     *
     * @return
     *         possible object is {@link String }
     *
     */
    public String getInputId()
    {
        return inputId;
    }


    /**
     * Sets the value of the inputId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setInputId(final String value)
    {
        this.inputId = value;
    }


    /**
     * Gets the value of the moduleUrl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getModuleUrl()
    {
        return moduleUrl;
    }


    /**
     * Sets the value of the moduleUrl property.
     *
     * @param moduleUrl
     *     allowed object is
     *     {@link String }
     *
     */
    public void setModuleUrl(final String moduleUrl)
    {
        this.moduleUrl = moduleUrl;
    }
}
