/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.29 at 06:03:31 PM MESZ
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WidgetRemoveAllEntry complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="WidgetRemoveAllEntry"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="contextId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="includeSettings" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WidgetRemoveAllEntry")
public class WidgetRemoveAllEntry
{
    @XmlAttribute
    protected String contextId;
    @XmlAttribute
    protected Boolean includeSettings;


    /**
     * Gets the value of the contextId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getContextId()
    {
        return contextId;
    }


    /**
     * Sets the value of the contextId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setContextId(final String value)
    {
        this.contextId = value;
    }


    /**
     * Gets the value of the includeSettings property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public boolean isIncludeSettings()
    {
        if(includeSettings == null)
        {
            return true;
        }
        else
        {
            return includeSettings.booleanValue();
        }
    }


    /**
     * Sets the value of the includeSettings property.
     *
     * @param value
     *           allowed object is {@link Boolean }
     *
     */
    public void setIncludeSettings(final Boolean value)
    {
        this.includeSettings = value;
    }
}
