/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.29 at 05:49:40 PM MESZ
//
package com.hybris.cockpitng.core.persistence.impl.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Widget complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Widget"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="widget" type="{}Widget" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="instance-settings" type="{}InstanceSettings" minOccurs="0"/&gt;
 *         &lt;element name="setting" type="{}WidgetSetting" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="widgetDefinitionId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="slotId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="template" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="lastFocusedChildIndex" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="lastFocusedTemplateInstanceId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Widget", propOrder = {"widget", "instanceSettings", "setting", "virtualSockets"})
public class Widget
{
    protected List<Widget> widget;
    @XmlElement(name = "instance-settings")
    protected InstanceSettings instanceSettings;
    protected List<WidgetSetting> setting;
    @XmlElement(name = "virtual-sockets")
    protected VirtualSockets virtualSockets;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    protected String widgetDefinitionId;
    @XmlAttribute
    protected String slotId;
    @XmlAttribute
    protected String title;
    @XmlAttribute
    protected Boolean template;
    @XmlAttribute
    protected BigInteger lastFocusedChildIndex;
    @XmlAttribute
    protected String lastFocusedTemplateInstanceId;
    @XmlAttribute
    protected String access;


    /**
     * Gets the value of the widget property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the widget property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getWidget().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Widget }
     *
     *
     */
    public List<Widget> getWidget()
    {
        if(widget == null)
        {
            widget = new ArrayList<Widget>();
        }
        return this.widget;
    }


    /**
     * Gets the value of the instanceSettings property.
     *
     * @return
     *         possible object is {@link InstanceSettings }
     *
     */
    public InstanceSettings getInstanceSettings()
    {
        return instanceSettings;
    }


    /**
     * Sets the value of the instanceSettings property.
     *
     * @param value
     *           allowed object is {@link InstanceSettings }
     *
     */
    public void setInstanceSettings(final InstanceSettings value)
    {
        this.instanceSettings = value;
    }


    /**
     * Gets the value of the setting property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the setting property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getSetting().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link WidgetSetting }
     *
     *
     */
    public List<WidgetSetting> getSetting()
    {
        if(setting == null)
        {
            setting = new ArrayList<WidgetSetting>();
        }
        return this.setting;
    }


    /**
     * Gets the value of the virtualSockets property.
     *
     * @return possible object is {@link VirtualSockets }
     *
     */
    public VirtualSockets getVirtualSockets()
    {
        return virtualSockets;
    }


    /**
     * Sets the value of the virtualSockets property.
     *
     * @param value
     *           allowed object is {@link VirtualSockets }
     *
     */
    public void setVirtualSockets(final VirtualSockets value)
    {
        this.virtualSockets = value;
    }


    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId()
    {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setId(final String value)
    {
        this.id = value;
    }


    /**
     * Gets the value of the widgetDefinitionId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getWidgetDefinitionId()
    {
        return widgetDefinitionId;
    }


    /**
     * Sets the value of the widgetDefinitionId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setWidgetDefinitionId(final String value)
    {
        this.widgetDefinitionId = value;
    }


    /**
     * Gets the value of the slotId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSlotId()
    {
        return slotId;
    }


    /**
     * Sets the value of the slotId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setSlotId(final String value)
    {
        this.slotId = value;
    }


    /**
     * Gets the value of the title property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTitle()
    {
        return title;
    }


    /**
     * Sets the value of the title property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setTitle(final String value)
    {
        this.title = value;
    }


    /**
     * Gets the value of the template property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public boolean isTemplate()
    {
        if(template == null)
        {
            return false;
        }
        else
        {
            return template.booleanValue();
        }
    }


    /**
     * Sets the value of the template property.
     *
     * @param value
     *           allowed object is {@link Boolean }
     *
     */
    public void setTemplate(final Boolean value)
    {
        this.template = value;
    }


    /**
     * Gets the value of the lastFocusedChildIndex property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getLastFocusedChildIndex()
    {
        return lastFocusedChildIndex;
    }


    /**
     * Sets the value of the lastFocusedChildIndex property.
     *
     * @param value
     *           allowed object is {@link BigInteger }
     *
     */
    public void setLastFocusedChildIndex(final BigInteger value)
    {
        this.lastFocusedChildIndex = value;
    }


    /**
     * Gets the value of the lastFocusedTemplateInstanceId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLastFocusedTemplateInstanceId()
    {
        return lastFocusedTemplateInstanceId;
    }


    /**
     * Sets the value of the lastFocusedTemplateInstanceId property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setLastFocusedTemplateInstanceId(final String value)
    {
        this.lastFocusedTemplateInstanceId = value;
    }


    /**
     * Gets the value of the access property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAccess()
    {
        return access;
    }


    /**
     * Sets the value of the access property.
     *
     * @param value
     *           allowed object is {@link String }
     *
     */
    public void setAccess(final String value)
    {
        this.access = value;
    }
}
