/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 09:29:30 AM CEST 
//
package com.hybris.cockpitng.core.config.impl.jaxb.hybris.commonconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for image-preview complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="image-preview"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="display-thumbnail" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="display-preview" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="display-default-image" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="default-image" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "image-preview")
public abstract class ImagePreview
{
    @XmlAttribute(name = "display-thumbnail")
    protected Boolean displayThumbnail;
    @XmlAttribute(name = "display-preview")
    protected Boolean displayPreview;
    @XmlAttribute(name = "display-default-image")
    protected Boolean displayDefaultImage;
    @XmlAttribute(name = "default-image")
    protected String defaultImage;


    /**
     * Gets the value of the displayThumbnail property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isDisplayThumbnail()
    {
        if(displayThumbnail == null)
        {
            return true;
        }
        else
        {
            return displayThumbnail;
        }
    }


    /**
     * Sets the value of the displayThumbnail property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDisplayThumbnail(Boolean value)
    {
        this.displayThumbnail = value;
    }


    /**
     * Gets the value of the displayPreview property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isDisplayPreview()
    {
        if(displayPreview == null)
        {
            return false;
        }
        else
        {
            return displayPreview;
        }
    }


    /**
     * Sets the value of the displayPreview property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDisplayPreview(Boolean value)
    {
        this.displayPreview = value;
    }


    /**
     * Gets the value of the displayDefaultImage property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isDisplayDefaultImage()
    {
        if(displayDefaultImage == null)
        {
            return true;
        }
        else
        {
            return displayDefaultImage;
        }
    }


    /**
     * Sets the value of the displayDefaultImage property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDisplayDefaultImage(Boolean value)
    {
        this.displayDefaultImage = value;
    }


    /**
     * Gets the value of the defaultImage property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDefaultImage()
    {
        return defaultImage;
    }


    /**
     * Sets the value of the defaultImage property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDefaultImage(String value)
    {
        this.defaultImage = value;
    }
}
