/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.09.02 at 05:29:07 PM CEST
//
package com.hybris.cockpitng.core.config.impl.jaxb;

import com.hybris.cockpitng.core.persistence.impl.jaxb.Import;
import com.hybris.cockpitng.core.persistence.impl.jaxb.Requirement;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="context" type="{http://www.hybris.com/cockpit/config}context" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "config", propOrder =
                {"requires", "context", "imports"})
@XmlRootElement(name = "config")
public class Config
{
    protected List<Context> context;
    @XmlElement(nillable = true, name = "import")
    private List<Import> imports;
    @XmlElement(nillable = true, name = "requires")
    private List<Requirement> requires;
    @XmlAttribute
    private String parameters;
    @XmlAttribute(name = "required-parameters")
    private String requiredParameters;


    /**
     * Gets the value of the context property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * context property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getContext().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Context }
     */
    public List<Context> getContext()
    {
        if(context == null)
        {
            context = new ArrayList<Context>();
        }
        return this.context;
    }


    public List<Import> getImports()
    {
        if(imports == null)
        {
            imports = new ArrayList<>();
        }
        return imports;
    }


    public List<Requirement> getRequires()
    {
        if(requires == null)
        {
            requires = new ArrayList<Requirement>();
        }
        return requires;
    }


    public String getParameters()
    {
        return parameters;
    }


    public void setParameters(final String parameters)
    {
        this.parameters = parameters;
    }


    public String getRequiredParameters()
    {
        return requiredParameters;
    }


    public void setRequiredParameters(final String requiredParameters)
    {
        this.requiredParameters = requiredParameters;
    }
}
