/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.01.29 at 10:33:44 AM CET
//
package com.hybris.cockpitng.config.dashboard.jaxb;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="grid" type="{http://www.hybris.com/cockpitng/config/dashboard}grid" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="defaultGridId" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"grid"})
@XmlRootElement(name = "dashboard", namespace = "http://www.hybris.com/cockpitng/config/dashboard")
public class Dashboard
{
    @XmlElement(required = true, namespace = "http://www.hybris.com/cockpitng/config/dashboard")
    @Mergeable(key = "id")
    protected List<Grid> grid;
    @XmlAttribute(name = "defaultGridId")
    @XmlSchemaType(name = "anySimpleType")
    protected String defaultGridId;


    /**
     * Gets the value of the grid property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grid property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getGrid().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Grid }
     *
     *
     */
    public List<Grid> getGrid()
    {
        if(grid == null)
        {
            grid = new ArrayList<Grid>();
        }
        return this.grid;
    }


    /**
     * Gets the value of the defaultGridId property.
     *
     * @return
     *            possible object is
     *         {@link String }
     *
     */
    public String getDefaultGridId()
    {
        return defaultGridId;
    }


    /**
     * Sets the value of the defaultGridId property.
     *
     * @param value
     *           allowed object is
     *           {@link String }
     *
     */
    public void setDefaultGridId(String value)
    {
        this.defaultGridId = value;
    }
}
