/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.12 at 12:22:01 PM CET 
//
package com.hybris.cockpitng.config.dashboard.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for grid complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="grid"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="placement" type="{http://www.hybris.com/cockpitng/config/dashboard}placement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="minScreenWidth" type="{http://www.hybris.com/cockpitng/config/dashboard}positiveInt" /&gt;
 *       &lt;attribute name="maxScreenWidth" type="{http://www.hybris.com/cockpitng/config/dashboard}positiveInt" /&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="merge-mode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="unassigned" type="{http://www.hybris.com/cockpitng/config/dashboard}unassignedBehavior" default="append" /&gt;
 *       &lt;attribute name="rowHeight" type="{http://www.hybris.com/cockpitng/config/dashboard}positiveInt" default="500" /&gt;
 *       &lt;attribute name="fluid" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grid", propOrder = {
                "placement"
})
public class Grid
{
    protected List<Placement> placement;
    @XmlAttribute(name = "minScreenWidth")
    protected Integer minScreenWidth;
    @XmlAttribute(name = "maxScreenWidth")
    protected Integer maxScreenWidth;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "merge-mode")
    protected String mergeMode;
    @XmlAttribute(name = "unassigned")
    protected UnassignedBehavior unassigned;
    @XmlAttribute(name = "rowHeight")
    protected Integer rowHeight;
    @XmlAttribute(name = "fluid")
    protected Boolean fluid;


    /**
     * Gets the value of the placement property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the placement property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlacement().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Placement }
     *
     *
     */
    public List<Placement> getPlacement()
    {
        if(placement == null)
        {
            placement = new ArrayList<Placement>();
        }
        return this.placement;
    }


    /**
     * Gets the value of the minScreenWidth property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getMinScreenWidth()
    {
        return minScreenWidth;
    }


    /**
     * Sets the value of the minScreenWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setMinScreenWidth(Integer value)
    {
        this.minScreenWidth = value;
    }


    /**
     * Gets the value of the maxScreenWidth property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getMaxScreenWidth()
    {
        return maxScreenWidth;
    }


    /**
     * Sets the value of the maxScreenWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setMaxScreenWidth(Integer value)
    {
        this.maxScreenWidth = value;
    }


    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId()
    {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value)
    {
        this.id = value;
    }


    /**
     * Gets the value of the mergeMode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMergeMode()
    {
        return mergeMode;
    }


    /**
     * Sets the value of the mergeMode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMergeMode(String value)
    {
        this.mergeMode = value;
    }


    /**
     * Gets the value of the unassigned property.
     *
     * @return
     *     possible object is
     *     {@link UnassignedBehavior }
     *
     */
    public UnassignedBehavior getUnassigned()
    {
        if(unassigned == null)
        {
            return UnassignedBehavior.APPEND;
        }
        else
        {
            return unassigned;
        }
    }


    /**
     * Sets the value of the unassigned property.
     *
     * @param value
     *     allowed object is
     *     {@link UnassignedBehavior }
     *
     */
    public void setUnassigned(UnassignedBehavior value)
    {
        this.unassigned = value;
    }


    /**
     * Gets the value of the rowHeight property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public int getRowHeight()
    {
        if(rowHeight == null)
        {
            return 500;
        }
        else
        {
            return rowHeight;
        }
    }


    /**
     * Sets the value of the rowHeight property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setRowHeight(Integer value)
    {
        this.rowHeight = value;
    }


    /**
     * Gets the value of the fluid property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isFluid()
    {
        if(fluid == null)
        {
            return false;
        }
        else
        {
            return fluid;
        }
    }


    /**
     * Sets the value of the fluid property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setFluid(Boolean value)
    {
        this.fluid = value;
    }
}
