/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.02.10 at 11:46:39 AM CET
//
package com.hybris.cockpitng.config.dashboard.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for placement complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="placement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="widgetId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="width" type="{http://www.hybris.com/cockpitng/config/dashboard}positiveInt" default="1" /&gt;
 *       &lt;attribute name="height" type="{http://www.hybris.com/cockpitng/config/dashboard}positiveInt" default="1" /&gt;
 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}int" default="0" /&gt;
 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}int" default="0" /&gt;
 *       &lt;attribute name="merge-mode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "placement")
public class Placement
{
    @XmlAttribute(name = "widgetId", required = true)
    protected String widgetId;
    @XmlAttribute(name = "width")
    protected Integer width;
    @XmlAttribute(name = "height")
    protected Integer height;
    @XmlAttribute(name = "x")
    protected Integer x;
    @XmlAttribute(name = "y")
    protected Integer y;
    @XmlAttribute(name = "merge-mode")
    protected String mergeMode;


    /**
     * Gets the value of the widgetId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWidgetId()
    {
        return widgetId;
    }


    /**
     * Sets the value of the widgetId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWidgetId(String value)
    {
        this.widgetId = value;
    }


    /**
     * Gets the value of the width property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public int getWidth()
    {
        if(width == null)
        {
            return 1;
        }
        else
        {
            return width;
        }
    }


    /**
     * Sets the value of the width property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setWidth(Integer value)
    {
        this.width = value;
    }


    /**
     * Gets the value of the height property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public int getHeight()
    {
        if(height == null)
        {
            return 1;
        }
        else
        {
            return height;
        }
    }


    /**
     * Sets the value of the height property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setHeight(Integer value)
    {
        this.height = value;
    }


    /**
     * Gets the value of the x property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public int getX()
    {
        if(x == null)
        {
            return 0;
        }
        else
        {
            return x;
        }
    }


    /**
     * Sets the value of the x property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setX(Integer value)
    {
        this.x = value;
    }


    /**
     * Gets the value of the y property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public int getY()
    {
        if(y == null)
        {
            return 0;
        }
        else
        {
            return y;
        }
    }


    /**
     * Sets the value of the y property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setY(Integer value)
    {
        this.y = value;
    }


    /**
     * Gets the value of the mergeMode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMergeMode()
    {
        return mergeMode;
    }


    /**
     * Sets the value of the mergeMode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMergeMode(String value)
    {
        this.mergeMode = value;
    }
}
