/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.29 at 10:33:44 AM CET 
//
package com.hybris.cockpitng.config.dashboard.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for unassignedBehavior.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="unassignedBehavior"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="append"/&gt;
 *     &lt;enumeration value="exclude"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "unassignedBehavior")
@XmlEnum
public enum UnassignedBehavior
{
    @XmlEnumValue("append")
    APPEND("append"),
    @XmlEnumValue("exclude")
    EXCLUDE("exclude");
    private final String value;


    UnassignedBehavior(String v)
    {
        value = v;
    }


    public String value()
    {
        return value;
    }


    public static UnassignedBehavior fromValue(String v)
    {
        for(UnassignedBehavior c : UnassignedBehavior.values())
        {
            if(c.value.equals(v))
            {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
