server:
  port: 8080
  shutdown: graceful
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

springdoc:
  packagesToScan: io.github.orionlibs.ecommerce.lifecycle.api
  writer-with-order-by-keys: true
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui

spring:
  application:
    name: Lifecycle Manager
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE

version: 0.0.1
environment: ${ENVIRONMENT_NAME:production}

app:
  default-config:
    default.printing.timezone: GB

# Production profile (default)
---
spring:
  config:
    activate:
      on-profile: "!test"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LIFECYCLE_DATABASE_URL}
    username: ${LIFECYCLE_DATABASE_USERNAME}
    password: ${LIFECYCLE_DATABASE_PASSWORD}
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      maxLifetime: 1800000
      connectionTimeout: 30000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob:
          non_contextual_creation: true
    #show-sql: true
    properties:
      hibernate:
        format_sql: true




---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;INIT=CREATE SCHEMA IF NOT EXISTS uns
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
  #  show-sql: true
    properties:
      hibernate.default_schema: uns
      hibernate.format_sql: true

  springdoc:
    packagesToScan: io.github.orionlibs.ecommerce.lifecycle.api
    writer-with-order-by-keys: true
    api-docs:
      enabled: true
      path: /api/docs
