/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.10.20 at 11:08:27 AM CEST
//
package com.hybris.cockpitng.core.config.impl.jaxb.listview;

import com.hybris.cockpitng.core.config.annotations.Mergeable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="column" type="{http://www.hybris.com/cockpitng/component/listView}list-column" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="refresh-after-object-creation" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="show-header" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
                "column"
})
@XmlRootElement(name = "list-view", namespace = "http://www.hybris.com/cockpitng/component/listView")
public class ListView
{
    @Mergeable(key = {"qualifier", "springBean"})
    @XmlElement(namespace = "http://www.hybris.com/cockpitng/component/listView", required = true)
    protected List<ListColumn> column;
    @XmlAttribute(name = "refresh-after-object-creation")
    protected Boolean refreshAfterObjectCreation;
    @XmlAttribute(name = "show-header")
    protected Boolean showHeader;


    /**
     * Gets the value of the column property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the column property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumn().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListColumn }
     *
     *
     */
    public List<ListColumn> getColumn()
    {
        if(column == null)
        {
            column = new ArrayList<ListColumn>();
        }
        return this.column;
    }


    /**
     * Gets the value of the refreshAfterObjectCreation property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean getRefreshAfterObjectCreation()
    {
        return refreshAfterObjectCreation;
    }


    /**
     * Sets the value of the refreshAfterObjectCreation property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setRefreshAfterObjectCreation(Boolean value)
    {
        this.refreshAfterObjectCreation = value;
    }


    /**
     * Gets the value of the showHeader property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isShowHeader()
    {
        if(showHeader == null)
        {
            return true;
        }
        else
        {
            return showHeader;
        }
    }


    /**
     * Sets the value of the showHeader property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setShowHeader(Boolean value)
    {
        this.showHeader = value;
    }
}
