/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.20 at 10:01:33 AM CEST 
//
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hybris.com/cockpitng/component/listView", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@XmlJavaTypeAdapter(type = String.class, value = StringTrimAdapter.class)
package com.hybris.cockpitng.core.config.impl.jaxb.listview;

import com.hybris.cockpitng.core.config.impl.jaxb.adapters.StringTrimAdapter;
