package de.hybris.platform.commercefacades.product;

public enum ProductOption
{
    PRICE, PRICE_RANGE, BASIC, SUMMARY, DESCRIPTION, GALLERY, CATEGORIES, PROMOTIONS, STOCK, REVIEW, CLASSIFICATION, VARIANT_FULL, REFERENCES, DELIVERY_MODE_AVAILABILITY, VARIANT_MATRIX, VARIANT_FIRST_VARIANT, VARIANT_MATRIX_BASE, VARIANT_MATRIX_ALL_OPTIONS, VARIANT_MATRIX_URL, VARIANT_MATRIX_MEDIA, VARIANT_MATRIX_PRICE, VARIANT_MATRIX_STOCK, URL, IMAGES, VOLUME_PRICES, KEYWORDS;
}
